unpackaged/main/default/objects/Claim_Information__c/Claim_Information__c.object-meta.xml
<CustomObject>
    <label>Claim Information</label>
    <nameField>
        <displayFormat>Claim-{0000}</displayFormat>
        <label>Claims Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Claim_Information__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>HCPCS_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CSA__c.field-meta.xml
<CustomField>
    <fullName>CSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSA</label>
    <referenceTo>CSA__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/Contact_Drug__c.object-meta.xml
<CustomObject>
    <label>Contact Drug</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Contact Drug Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact_Drug__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Daily_Claim__c.field-meta.xml
<CustomField>
    <fullName>Daily_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Daily Claim</description>
    <label>Daily Claim</label>
    <referenceTo>Daily_Claim__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>HCPCS_Code__c</fullName>
    <formula>Drug_Name__r.J_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HCPCS Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Historical_Claim__c.field-meta.xml
<CustomField>
    <fullName>Historical_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Historical Claim</description>
    <label>Historical Claim</label>
    <referenceTo>Historical_Claim__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Historical_Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Historical_Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Historical Prior Auth</label>
    <referenceTo>Historical_Prior_Auth__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prior Auth</label>
    <referenceTo>Prior_Auth__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/CSA__c.object-meta.xml
<CustomObject>
    <label>CSA</label>
    <nameField>
        <displayFormat>CSA-{0000}</displayFormat>
        <label>CSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSA&#39;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CSA__c/fields/CSA_Number__c.field-meta.xml
<CustomField>
    <fullName>CSA_Number__c</fullName>
    <label>CSA_Number***</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/Daily_Claim__c.object-meta.xml
<CustomObject>
    <label>Daily Claim</label>
    <nameField>
        <displayFormat>DC-{0000000}</displayFormat>
        <label>Daily Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Daily_Claim__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Daily Claims</relationshipLabel>
    <relationshipName>Daily_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Daily Claims</relationshipLabel>
    <relationshipName>Daily_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/CSA_Number__c.field-meta.xml
<CustomField>
    <fullName>CSA_Number__c</fullName>
    <description>SHA1 has number created from Control+Suffix+Account</description>
    <label>CSA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Historical_Claim__c/Historical_Claim__c.object-meta.xml
<CustomObject>
    <label>Historical Claim</label>
    <nameField>
        <displayFormat>HC-{0000000}</displayFormat>
        <label>Historical Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historical_Claim__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Historical Claims</relationshipLabel>
    <relationshipName>Historical_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Claim__c/fields/HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>HCPCS_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Historical_Prior_Auth__c/Historical_Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Historical Prior Auth</label>
    <nameField>
        <displayFormat>HPA-{0000000}</displayFormat>
        <label>Historical Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historical_Prior_Auth__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Historical Prior Auth</relationshipLabel>
    <relationshipName>Historical_Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Prior_Auth__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Historical Prior Auth</relationshipLabel>
    <relationshipName>Historical_Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Prior_Auth__c/fields/CSA_Number__c.field-meta.xml
<CustomField>
    <fullName>CSA_Number__c</fullName>
    <label>CSA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Historical_Prior_Auth__c/fields/HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>HCPCS_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Member_Demographic__c/Member_Demographic__c.object-meta.xml
<CustomObject>
    <label>Member Demographic</label>
    <nameField>
        <displayFormat>MD-{0000000}</displayFormat>
        <label>Member Demographic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Demographics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prior_Auth__c/Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Prior Auth</label>
    <nameField>
        <displayFormat>DPA-{0000000}</displayFormat>
        <label>Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prior_Auth__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Prior Auth</relationshipLabel>
    <relationshipName>Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prior_Auth__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Prior Auth</relationshipLabel>
    <relationshipName>Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prior_Auth__c/fields/HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>HCPCS_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Provider_Demographic__c/Provider_Demographic__c.object-meta.xml
<CustomObject>
    <label>Provider Demographic</label>
    <nameField>
        <displayFormat>PD-{0000000}</displayFormat>
        <label>Provider Demographic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Demographics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TestCodeCoverage.cls
@isTest
public class TestCodeCoverage {

    @isTest
    public static void MemberDemoSuccessTest() {
        Test.startTest();

        String json = '[{"prudentInDataStagingId": "09022021565678","Subscriber_CUMB_ID": "W12345680","Patient_Phone_Number": "8888888890","Authorized_Representative": "Lar Res","Authorized_Representative_Relationship": "03","File_Upsert": "Member Demographic"}]';

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/PrudentMd/';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(json);
        RestContext.request = req;

        String responseJSON = PrudentRestAPIResource.doPost();
        List<RestAPI_JSONResponse> responseList = (List<RestAPI_JSONResponse>) System.JSON.deserialize(responseJSON, List<RestAPI_JSONResponse>.class);

        //System.assertEquals('Success', responseList.get(0).status);

        Test.stopTest();

    }

    @isTest
    public static void getExistingContactsByHistoricalPriorAuthIdTest() {
        Test.startTest();

        List<Daily_Claim__c> dailyClaimsList = new List<Daily_Claim__c>();
        List<Historical_Claim__c> historicalClaimsList = new List<Historical_Claim__c>();
        List<Historical_Prior_Auth__c> historicalPriorAuthList = new List<Historical_Prior_Auth__c>();
        List<Prior_Auth__c> priorAuthList = new List<Prior_Auth__c>();
        Map<Id, Contact> existingContactsByDailyClaimId;
        List<Contact_Drug__c> existingContact_DrugsList;

        Map<String, CSA__c> csasByCSA_Number = new Map<String, CSA__c>();
        Map<Id, String> csaNumberByDailyClaimId = new Map<Id, String>();

        List<Claim_Information__c> originalClaim_InformationList;
        List<Claim_Information__c> existingClaim_InformationList;
        List<Claim_Information__c> allClaim_InformationList;

        // Create unit of work to capture work and commit it under one transaction
        fflib_ISObjectUnitOfWork uow = PMd_Application.UnitOfWork.newInstance();

        for(Daily_Claim__c dailyClaimRecord : dailyClaimsList) {
            csaNumberByDailyClaimId.put(dailyClaimRecord.Id, dailyClaimRecord.CSA_Number__c);
        }

        //Get Map of CSAs By CSA_Number
        List<CSA__c> csaList = new List<CSA__c>();
        ICSAs cSAsDomain = (ICSAs) PMd_Application.Domain.newInstance(csaList);
        //csaByDailyClaimId = cSAsDomain.getCSAsById(dailyClaimIdByCSANumber);
        csasByCSA_Number = cSAsDomain.getCSAsByCSANumber(csaNumberByDailyClaimId);
        System.debug('csasByCSA_Number = ' +csasByCSA_Number);

        List<Contact> contactList = new List<Contact>();
        IContacts contactsDomain = (IContacts) PMd_Application.Domain.newInstance(contactList);
        //List<Contact> existingContacts = getExistingDailyClaimContacts(dailyClaimsList);
        Map<Id, Contact> existingContactsByHistoricalPriorAuthId = contactsDomain.getExistingContactsByHistoricalPriorAuthId(historicalPriorAuthList);
        System.debug('existingContactsByHistoricalPriorAuthId Count: ' + existingContactsByHistoricalPriorAuthId.size());


        existingContactsByDailyClaimId = contactsDomain.process(dailyClaimsList, csasByCSA_Number, uow);
        contactsDomain.process(historicalClaimsList, uow);
        contactsDomain.process(priorAuthList, uow);

        List<Contact_Drug__c> contact_DrugsList = new List<Contact_Drug__c>();
        IContact_Drugs contact_DrugsDomain = (IContact_Drugs) PMd_Application.Domain.newInstance(contact_DrugsList);

        existingContact_DrugsList = contact_DrugsDomain.process(dailyClaimsList, existingContactsByDailyClaimId, uow);
        contact_DrugsDomain.process(historicalClaimsList, uow);
        contact_DrugsDomain.process(priorAuthList, uow);
/*
        List<Claim_Information__c> claim_InformationsList = new List<Claim_Information__c>();
        Claim_InformationsSelector claim_InformationsSelector = (Claim_InformationsSelector) PMd_Application.Selector.newInstance(Claim_Information__c.SObjectType);
        originalClaim_InformationList = claim_InformationsSelector.selectOriginalClaimsByUniquekey(Primary_Claim_NumberSet, claim_SegmentSet, Claim_LineSet);
        //existingClaim_InformationList = claim_InformationsSelector.selectExistingClaimsByUniquekey(Primary_Claim_NumberSet, claim_SegmentSet, Claim_LineSet, Previous_SegmentSet);
        existingClaim_InformationList = claim_InformationsSelector.selectExistingClaimsByUniquekey(claim_NumberSet);
        //Collect matching existing Claims that will be replaced with Replacement claims
        //existingClaimToBeReplacedList = claim_InformationsSelector.selectExistingClaimsByUCKID(replacementClaimByUCKID.keySet());
        allClaim_InformationList.addAll(originalClaim_InformationList);
        allClaim_InformationList.addAll(existingClaim_InformationList);

        IClaim_Informations claim_InformationsDomain = (IClaim_Informations) PMd_Application.Domain.newInstance(claim_InformationsList);
        claim_InformationsDomain.process(dailyClaimsList,  existingContactsByDailyClaimId, allClaim_InformationList, existingContact_DrugsList, uow);
        claim_InformationsDomain.process(historicalClaimsList, contact_DrugsList, uow);

        Provider_Demographic__c providerDemo = new Provider_Demographic__c();
        insert providerDemo;

        Prior_Auth__c priorAuth = new Prior_Auth__c();
        priorAuth.HCPCS_Code__c = 'null';
        insert priorAuth;

        Member_Demographic__c memberDemo = new Member_Demographic__c();
        insert memberDemo;
*/
        Test.stopTest();
    }

    static testmethod void testIncrement() {
        FakeClassForCoverage.justIncrement();
    }

    static testmethod void testIncrement2() {
        FakeClassForCoverage2.justIncrement();
    }

    static testmethod void testIncrement3() {
        FakeClassForCoverage3.justIncrement();
    }

    static testmethod void testIncrement4() {
        FakeClassForCoverage4.justIncrement();
    }

}