unpackaged/main/default/objects/Claim_Information__c/Claim_Information__c.object-meta.xml
<CustomObject>
    <label>Claim Information</label>
    <nameField>
        <displayFormat>Claim-{0000}</displayFormat>
        <label>Claims Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Claim_Information__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>HCPCS_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/NDC__c.field-meta.xml
<CustomField>
    <fullName>NDC__c</fullName>
    <inlineHelpText>NDC may not always be provided</inlineHelpText>
    <label>NDC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/Contact_Drug__c.object-meta.xml
<CustomObject>
    <label>Contact Drug</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Contact Drug Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact_Drug__c/fields/Alternative_Phone__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Phone__c</fullName>
    <formula>Contact__r.Alternative_Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternative Phone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Authorization_Received__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Received__c</fullName>
    <formula>Contact__r.Authorization_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Authorization Received</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <formula>Contact__r.Patient_Birth_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Copay_Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Copay_Enrollment_Status__c</fullName>
    <label>CPA Enrollment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not on File</fullName>
                <default>true</default>
                <label>Not on File</label>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>On File</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Drug_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug Name</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>HCPCS_Code__c</fullName>
    <formula>Drug_Name__r.J_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HCPCS Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Historical_Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Historical_Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Historical Prior Auth</label>
    <referenceTo>Historical_Prior_Auth__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Member_Ineligible_for_CPA__c.field-meta.xml
<CustomField>
    <fullName>Member_Ineligible_for_CPA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Member Ineligible for CPA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Drug__c/Drug__c.object-meta.xml
<CustomObject>
    <description>The Main Drug Table</description>
    <label>Drug</label>
    <nameField>
        <label>Drug Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Drug__c/fields/Coding_Level__c.field-meta.xml
<CustomField>
    <fullName>Coding_Level__c</fullName>
    <label>Coding Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCPCS</fullName>
            </value>
            <value>
                <fullName>HCPCS + NDC</fullName>
            </value>
            <value>
                <fullName>HCPCS + DX</fullName>
            </value>
            <value>
                <fullName>ICD -10</fullName>
                <isActive>false</isActive>
                <label>ICD -10</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Historical_Prior_Auth__c/Historical_Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Historical Prior Auth</label>
    <nameField>
        <displayFormat>HPA-{0000000}</displayFormat>
        <label>Historical Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historical_Prior_Auth__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Historical Prior Auth</relationshipLabel>
    <relationshipName>Historical_Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Prior_Auth__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Historical Prior Auth</relationshipLabel>
    <relationshipName>Historical_Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Prior_Auth__c/fields/HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>HCPCS_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NDC__c/NDC__c.object-meta.xml
<CustomObject>
    <description>Drugs are identified and reported using a unique, three-segment number called the National Drug Code (NDC) which serves as the FDA’s identifier for drugs.</description>
    <label>NDC</label>
    <nameField>
        <label>NDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/Contact_DrugsSelector.cls
/**
 * @description       : Contact_Drugs Selector Implementation
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             :
 * @last modified on  : 08-05-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log
 * Ver   Date         Author                           Modification
 * 1.0   08-05-2021   Ricardy Banks					   Initial Version
 *
 **/

public class Contact_DrugsSelector extends fflib_SObjectSelector
        implements IContact_DrugsSelector
{

    public Contact_DrugsSelector() {
        super(false, true, true, false);
    }

    public static IContact_DrugsSelector newInstance() {
        return (IContact_DrugsSelector) PMd_Application.Selector.newInstance(Contact_Drug__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Contact_Drug__c.Id,
                Contact_Drug__c.Name,
                Contact_Drug__c.Alternative_Phone__c,
                Contact_Drug__c.Authorization_Received__c,
                Contact_Drug__c.Birthdate__c,
                Contact_Drug__c.Claim_Information__c,
                Contact_Drug__c.Contact__c,
                Contact_Drug__c.Copay_Enrollment_Status__c,
                Contact_Drug__c.Member_Ineligible_for_CPA__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Contact_Drug__c.SObjectType;
    }

    public List<Contact_Drug__c> selectById(Set<Id> idSet)
    {
        return (List<Contact_Drug__c>) selectSObjectsById(idSet);
    }

    public List<Contact_Drug__c> selectByContact_DrugId(Set<Id> contact_DrugIds) {

        return (List<Contact_Drug__c>) Database.query(
                newQueryFactory().
                        selectField(Contact_Drug__c.Phone__c).
                        selectField(Contact_Drug__c.OwnerId).
                        selectField(Contact_Drug__c.Email__c).
                        selectField(Contact_Drug__c.Birthdate__c).
                        selectField(Contact_Drug__c.Contact__c).
                        selectField(Contact_Drug__c.Claim_Information__c).
                        setCondition('Id IN :contact_DrugIds').
                        //setCondition('Patient_First_Name__c IN :firstName').
                        //setCondition('Patient_Last_Name__c IN :lastName').
                        toSOQL()
        );
    }

    public List<Contact_Drug__c> selectByJ_CodeIdContactId(Set<String> j_CodeIds, Set<String> NDCSet, Set<Id> contactIds) {

        String whereClause = 'HCPCS_Code__c IN :\'' + j_CodeIds + '\' AND NDC__c IN : \'' + NDCSet + '\' AND Contact__c IN : \'' + contactIds;
        System.debug('selectByJ_CodeIdContactId: query = ' + whereClause);

        System.debug('selectByJ_CodeIdContactId.toSOQL() = ' + newQueryFactory().
                selectField(Contact_Drug__c.Phone__c).
                selectField(Contact_Drug__c.OwnerId).
                selectField(Contact_Drug__c.Email__c).
                selectField(Contact_Drug__c.Birthdate__c).
                selectField(Contact_Drug__c.Contact__c).
                selectField(Contact_Drug__c.HCPCS_Code__c).
                selectField(Contact_Drug__c.Claim_Information__c).
                setCondition('HCPCS_Code__c IN :j_CodeIds AND Contact__c IN :contactIds').
                //setCondition('HCPCS_Code__c IN :j_CodeIds').
                //setCondition('NDC__c IN :NDCSet').
                //setCondition('Contact__c IN :contactIds').
                //setCondition('Patient_Last_Name__c IN :lastName').
                toSOQL()
        );

        return (List<Contact_Drug__c>) Database.query(
                newQueryFactory().
                        selectField(Contact_Drug__c.Phone__c).
                        selectField(Contact_Drug__c.OwnerId).
                        selectField(Contact_Drug__c.Email__c).
                        selectField(Contact_Drug__c.Birthdate__c).
                        selectField(Contact_Drug__c.Contact__c).
                        selectField(Contact_Drug__c.HCPCS_Code__c).
                        selectField(Contact_Drug__c.Claim_Information__c).
                        selectField('Drug_Name__r.Coding_Level__c').
                        setCondition('HCPCS_Code__c IN :j_CodeIds AND Contact__c IN :contactIds').
                        //setCondition('HCPCS_Code__c IN :j_CodeIds').
                        //setCondition('NDC__c IN :NDCSet').
                        //setCondition('Contact__c IN :contactIds').
                        //setCondition('Patient_Last_Name__c IN :lastName').
                        toSOQL()
        );
    }
/*
    public List<Contact_Drug__c> selectByContactId(Set<Id> contactIds) {

        return (List<Contact_Drug__c>) Database.query(
                newQueryFactory().
                        selectField(Contact_Drug__c.Phone__c).
                        selectField(Contact_Drug__c.OwnerId).
                        selectField(Contact_Drug__c.Email__c).
                        selectField(Contact_Drug__c.Birthdate__c).
                        selectField(Contact_Drug__c.Contact__c).
                        selectField(Contact_Drug__c.HCPCS_Code__c).
                        selectField(Contact_Drug__c.Historical_Prior_Auth__c).
                        setCondition('Contact__c IN :contactIds').
                        //setCondition('Contact__c IN :contactIds').
                        //setCondition('Patient_Last_Name__c IN :lastName').
                        toSOQL()
        );
    }
*/
    /*
    public List<Contact_Drug__c> selectByJ_CodeIdContactId(Set<String> j_CodeIds) {

        return (List<Contact_Drug__c>) Database.query(
                newQueryFactory().
                        selectField(Contact_Drug__c.Phone__c).
                        selectField(Contact_Drug__c.OwnerId).
                        selectField(Contact_Drug__c.Email__c).
                        selectField(Contact_Drug__c.Birthdate__c).
                        selectField(Contact_Drug__c.Contact__c).
                        selectField(Contact_Drug__c.HCPCS_Code__c).
                        setCondition('HCPCS_Code__c IN :j_CodeIds').
                        //setCondition('Patient_Last_Name__c IN :lastName').
                        toSOQL()
        );
    }
    */
}