unpackaged/main/default/objects/Claim_Information__c/Claim_Information__c.object-meta.xml
<CustomObject>
    <label>Claim Information</label>
    <nameField>
        <displayFormat>Claim-{0000}</displayFormat>
        <label>Claims Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Claim_Information__c/fields/Claim_Adjustment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Claim_Adjustment_Amount__c</fullName>
    <label>Claim Adjustment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Claim_Line__c.field-meta.xml
<CustomField>
    <fullName>Claim_Line__c</fullName>
    <label>Claim Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <label>Claim Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Claim_Segment__c.field-meta.xml
<CustomField>
    <fullName>Claim_Segment__c</fullName>
    <label>Claim Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <formula>CASE( Claim_Code__c ,
&#39;O&#39;, &#39;Original&#39;,
&#39;A&#39;, &#39;Adjustment&#39;,
&#39;R&#39;, &#39;Rework&#39;,
&#39;J&#39;, &#39;Reject&#39;,
&#39;V&#39;, &#39;Void&#39;,
&#39;C&#39;, &#39;Closeout&#39;,
&#39;&#39;
)</formula>
    <label>Claim Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/CPA_Funds_Paid__c.field-meta.xml
<CustomField>
    <fullName>CPA_Funds_Paid__c</fullName>
    <label>CPA Funds Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/CPA_Indicator__c.field-meta.xml
<CustomField>
    <fullName>CPA_Indicator__c</fullName>
    <label>CPA Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opt-in - Paid in full</fullName>
            </value>
            <value>
                <fullName>Opt-in - Partial payment</fullName>
            </value>
            <value>
                <fullName>Opt-in - Funds exhausted</fullName>
            </value>
            <value>
                <fullName>Opt-in - CPA not available</fullName>
            </value>
            <value>
                <fullName>Opt-in - Reimbursement not Confirmed</fullName>
            </value>
            <value>
                <fullName>Opt-out - Refused</fullName>
            </value>
            <value>
                <fullName>Opt-out - Member not Enrolled</fullName>
            </value>
            <value>
                <fullName>Opt-In: CPA Available</fullName>
                <isActive>false</isActive>
                <label>Opt-In: CPA Available</label>
            </value>
            <value>
                <fullName>Opt-Out: MBR Refused</fullName>
                <isActive>false</isActive>
                <label>Opt-Out: MBR Refused</label>
            </value>
            <value>
                <fullName>Opt-Out: MBR UTC</fullName>
                <isActive>false</isActive>
                <label>Opt-Out: MBR UTC</label>
            </value>
            <value>
                <fullName>Opt-out - CPA not confirmed</fullName>
                <isActive>false</isActive>
                <label>Opt-out - CPA not confirmed</label>
            </value>
            <value>
                <fullName>Opt-out - Reimbursement not Confirmed</fullName>
                <isActive>false</isActive>
                <label>Opt-out - Reimbursement not Confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Current_Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Current_Claim_Number__c</fullName>
    <description>Current Claim Number Key for Claim ID, Claim Segment, Claim Line, &amp; Previous Segment on the claim.</description>
    <label>Current Claim Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Date_Of_Service_From__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Service_From__c</fullName>
    <label>Date Of Service From</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Drug_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Brand_Name__c</fullName>
    <formula>Drug__r.Drug_Brand_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drug Brand Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Drug_Cost_Paid_by_Primary_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Drug_Cost_Paid_by_Primary_Insurance__c</fullName>
    <label>Drug Cost Paid by Primary Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Drug_Generic_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Generic_Name__c</fullName>
    <formula>Drug__r.Drug_Generic_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drug Generic Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Drug_Label_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Label_Name__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp; Drug__r.Id, Drug__r.Name,&quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drug Label Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/EOP_Date__c.field-meta.xml
<CustomField>
    <fullName>EOP_Date__c</fullName>
    <label>EOP Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>HCPCS_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Is_there_another_Health_Benefit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Is_there_another_Health_Benefit_Plan__c</fullName>
    <formula>TEXT( Contact_Drug__r.Contact__r.Is_there_a_Secondary_Insurance_Plan__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Does the patient have medical benefits and/or pharmacy benefits through any private or government health insurer/payer/program? Y/N</inlineHelpText>
    <label>Is there a Secondary Insurance Plan?</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/NDC__c.field-meta.xml
<CustomField>
    <fullName>NDC__c</fullName>
    <inlineHelpText>NDC may not always be provided</inlineHelpText>
    <label>NDC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/PA_Approval_Dates__c.field-meta.xml
<CustomField>
    <fullName>PA_Approval_Dates__c</fullName>
    <label>PA Approval Dates</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Previous_Claim__c.field-meta.xml
<CustomField>
    <fullName>Previous_Claim__c</fullName>
    <label>Previous Claim</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Previous_Segment__c.field-meta.xml
<CustomField>
    <fullName>Previous_Segment__c</fullName>
    <label>Previous Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Primary_Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Claim_Number__c</fullName>
    <label>Primary Claim Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/Contact_Drug__c.object-meta.xml
<CustomObject>
    <label>Contact Drug</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Contact Drug Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact_Drug__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Drug_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Brand_Name__c</fullName>
    <description>Drug Brand Name</description>
    <formula>Drug_Name__r.Drug_Brand_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drug Brand Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/GPI_14__c.field-meta.xml
<CustomField>
    <fullName>GPI_14__c</fullName>
    <formula>Drug_Name__r.GPI_14__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GPI 14</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/HCPCS_Code__c.field-meta.xml
<CustomField>
    <fullName>HCPCS_Code__c</fullName>
    <formula>Drug_Name__r.J_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HCPCS Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Drug__c/Drug__c.object-meta.xml
<CustomObject>
    <description>The Main Drug Table</description>
    <label>Drug</label>
    <nameField>
        <label>Drug Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Drug__c/fields/Drug_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Brand_Name__c</fullName>
    <label>Drug Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Drug__c/fields/Drug_Generic_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Generic_Name__c</fullName>
    <label>Drug Generic Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Drug__c/fields/GPI_14__c.field-meta.xml
<CustomField>
    <fullName>GPI_14__c</fullName>
    <label>GPI 14</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NDC__c/NDC__c.object-meta.xml
<CustomObject>
    <description>Drugs are identified and reported using a unique, three-segment number called the National Drug Code (NDC) which serves as the FDA’s identifier for drugs.</description>
    <label>NDC</label>
    <nameField>
        <label>NDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NDC__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>NDCs</relationshipLabel>
    <relationshipName>NDCs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/Claim_InformationsSelector.cls
/**
 * @description       : Claim_Information__c Selector Implementation
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             :
 * @last modified on  : 08-05-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log
 * Ver   Date         Author                           Modification
 * 1.0   08-05-2021   Ricardy Banks					   Initial Version
 *
 **/

public class Claim_InformationsSelector extends fflib_SObjectSelector
    implements IClaim_InformationsSelector
{

    public Claim_InformationsSelector() {
        super(false, true, true, false);
    }

    public static IClaim_InformationsSelector newInstance() {
        return (IClaim_InformationsSelector) PMd_Application.Selector.newInstance(Claim_Information__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Claim_Information__c.Id,
                Claim_Information__c.Name,
                //Claim_Information__c.Cardholder_s_Name__c,
                Claim_Information__c.Contact_Drug__c,
                Claim_Information__c.CPA_Funds_Paid__c,
                Claim_Information__c.CPA_Indicator__c,
                Claim_Information__c.CreatedById,
                Claim_Information__c.Date_Of_Service_From__c,
                Claim_Information__c.Drug__c,
                Claim_Information__c.Drug_Brand_Name__c,
                Claim_Information__c.Drug_Cost_Paid_by_Primary_Insurance__c,
                Claim_Information__c.Drug_Generic_Name__c,
                Claim_Information__c.Drug_Label_Name__c,
                //Claim_Information__c.NDC__c,
                //Claim_Information__c.GPI_14__c,
                //Claim_Information__c.Insurance_Plan_Name__c,
                Claim_Information__c.Is_there_another_Health_Benefit_Plan__c,
                Claim_Information__c.HCPCS_Code__c,
                Claim_Information__c.LastModifiedById,
                Claim_Information__c.Previous_Segment__c,
                Claim_Information__c.EOP_Date__c,
                Claim_Information__c.Claim_Status__c,
                Claim_Information__c.Claim_Adjustment_Amount__c
                //Claim_Information__c.Total_Drug_Cost__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Claim_Information__c.SObjectType;
    }

    public List<Claim_Information__c> selectById(Set<Id> idSet)
    {
        return (List<Claim_Information__c>) selectSObjectsById(idSet);
    }

    public List<Claim_Information__c> selectByContactId(Set<Id> contactIds) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        setCondition('Contact__c IN :contactIds').
                        //setCondition('Patient_First_Name__c IN :firstName').
                        //setCondition('Patient_Last_Name__c IN :lastName').
                        toSOQL()
        );
    }

    public List<Claim_Information__c> selectByPrimary_Claim_Number(Set<String> primary_Claim_NumberSet) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        setCondition('Primary_Claim_Number__c IN :primary_Claim_NumberSet').
                        //setCondition('Patient_First_Name__c IN :firstName').
                        //setCondition('Patient_Last_Name__c IN :lastName').
                        toSOQL()
        );
    }

    public List<Claim_Information__c> selectOriginalClaimsByPrimaryClaimNumber(Set<String> Primary_Claim_NumberSet) {

        Set<String> claim_SegmentSet = new Set<String>{'00'}; //All Original Claims will have a Claim Segment of 00

        System.debug('selectOriginalClaimsByPrimaryClaimNumber = ' + newQueryFactory().
                selectField(Claim_Information__c.Id).
                selectField(Claim_Information__c.OwnerId).
                selectField(Claim_Information__c.Name).
                //selectField(Claim_Information__c.Cardholder_s_Name__c).
                selectField(Claim_Information__c.Contact__c).
                selectField(Claim_Information__c.Primary_Claim_Number__c).
                selectField(Claim_Information__c.Claim_Number__c).
                selectField(Claim_Information__c.Current_Claim_Number__c).
                selectField(Claim_Information__c.Previous_Segment__c).
                selectField(Claim_Information__c.Date_Of_Service_From__c).
                selectField(Claim_Information__c.EOP_Date__c).
                //selectField(Claim_Information__c.Total_Drug_Cost__c).
                //setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet AND Claim_Segment__c IN :claim_SegmentSet AND Claim_Line__c IN :Claim_LineSet').
                setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet  AND Claim_Segment__c = \'00\'').
                //setCondition('Claim_Segment__c = \'00\'').
                //setCondition('Claim_Line__c IN :Claim_LineSet').
                toSOQL()
        );

        return (List<Claim_Information__c>) Database.query(newQueryFactory().
                selectField(Claim_Information__c.Id).
                selectField(Claim_Information__c.OwnerId).
                selectField(Claim_Information__c.Name).
                //selectField(Claim_Information__c.Cardholder_s_Name__c).
                selectField(Claim_Information__c.Contact__c).
                selectField(Claim_Information__c.Primary_Claim_Number__c).
                selectField(Claim_Information__c.Claim_Number__c).
                selectField(Claim_Information__c.Current_Claim_Number__c).
                selectField(Claim_Information__c.Previous_Segment__c).
                selectField(Claim_Information__c.EOP_Date__c).
                //selectField(Claim_Information__c.Total_Drug_Cost__c).
                //setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet AND Claim_Segment__c IN :claim_SegmentSet AND Claim_Line__c IN :Claim_LineSet').
                setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet  AND Claim_Segment__c = \'00\'').
                //setCondition('Claim_Segment__c = \'00\'').
                //setCondition('Claim_Line__c IN :Claim_LineSet').
                toSOQL()
        );
    }

    public List<Claim_Information__c> selectOriginalClaimsByUniquekey(Set<String> Primary_Claim_NumberSet, Set<String> claim_SegmentSet, Set<String> Claim_LineSet) {

        System.debug('selectOriginalClaimsByUniquekey = ' + newQueryFactory().
                selectField(Claim_Information__c.Id).
                selectField(Claim_Information__c.OwnerId).
                selectField(Claim_Information__c.Name).
                //selectField(Claim_Information__c.Cardholder_s_Name__c).
                selectField(Claim_Information__c.Contact__c).
                selectField(Claim_Information__c.Primary_Claim_Number__c).
                selectField(Claim_Information__c.Claim_Number__c).
                selectField(Claim_Information__c.Current_Claim_Number__c).
                selectField(Claim_Information__c.Previous_Segment__c).
                selectField(Claim_Information__c.Date_Of_Service_From__c).
                selectField(Claim_Information__c.EOP_Date__c).
                //selectField(Claim_Information__c.Total_Drug_Cost__c).
                //setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet AND Claim_Segment__c IN :claim_SegmentSet AND Claim_Line__c IN :Claim_LineSet').
                setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet AND Claim_Segment__c IN :claim_SegmentSet AND Claim_Line__c IN :Claim_LineSet').
                //setCondition('Claim_Segment__c IN :claim_SegmentSet').
                //setCondition('Claim_Line__c IN :Claim_LineSet').
                toSOQL()
        );

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        //setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet AND Claim_Segment__c IN :claim_SegmentSet AND Claim_Line__c IN :Claim_LineSet').
                        setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet AND Claim_Segment__c IN :claim_SegmentSet AND Claim_Line__c IN :Claim_LineSet').
                        //setCondition('Claim_Segment__c IN :claim_SegmentSet').
                        //setCondition('Claim_Line__c IN :Claim_LineSet').
                        toSOQL()
        );
    }

    public List<Claim_Information__c> selectOriginalClaimsByUniquekey(Set<String> Primary_Claim_NumberSet, Set<String> Claim_LineSet) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        //setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet AND Claim_Line__c IN :Claim_LineSet').
                        setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet').
                        //setCondition('Claim_Segment__c IN :claim_SegmentSet').
                        setCondition('Claim_Line__c IN :Claim_LineSet').
                        toSOQL()
        );
    }

    public List<Claim_Information__c> selectExistingClaimsByUniquekey(Set<String> Primary_Claim_NumberSet, Set<String> claim_SegmentSet, Set<String> Claim_LineSet , Set<String>  Previous_SegmentSet) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        selectField(Claim_Information__c.PA_Approval_Dates__c).
                        selectField(Claim_Information__c.Date_Of_Service_From__c).
                        selectField(Claim_Information__c.Previous_Claim__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet AND Claim_Line__c IN :Claim_LineSet AND Previous_Segment__c IN :Previous_SegmentSet').
                        //setCondition('Claim_Line__c IN :Claim_LineSet').
                        //setCondition('Previous_Segment__c IN :Previous_SegmentSet').
                        addOrdering('Date_Of_Service_From__c', fflib_QueryFactory.SortOrder.DESCENDING).
                        toSOQL()
        );
    }

    //SOQL Order is not working. I believe it is because the records are being updated & inserted in the same transaction.
    //Sort recordy be decending Date_Of_Service_From__c
    public List<Claim_Information__c> selectExistingClaimsByUniquekey(Set<String> Primary_Claim_NumberSet, Set<String> claim_SegmentSet, Set<String> Claim_LineSet) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        selectField(Claim_Information__c.PA_Approval_Dates__c).
                        selectField(Claim_Information__c.Date_Of_Service_From__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet').
                        setCondition('Claim_Line__c IN :Claim_LineSet').
                        //setCondition('Previous_Segment__c IN :Previous_SegmentSet').
                        addOrdering('Date_Of_Service_From__c', fflib_QueryFactory.SortOrder.DESCENDING).
                        toSOQL()
        );
    }

    //SOQL Order is not working. I believe it is because the records are being updated & inserted in the same transaction.
    //Sort records by descending Date_Of_Service_From__c
    public List<Claim_Information__c> selectExistingClaimsByUniquekey(Set<String> Primary_Claim_NumberSet, Set<String> claim_SegmentSet, Set<String> Claim_LineSet , Set<String>  Previous_SegmentSet, Set<Id> contactIdSet) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        selectField(Claim_Information__c.PA_Approval_Dates__c).
                        selectField(Claim_Information__c.Date_Of_Service_From__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        setCondition('Primary_Claim_Number__c IN :Primary_Claim_NumberSet').
                        setCondition('Claim_Line__c IN :Claim_LineSet').
                        setCondition('Previous_Segment__c IN :Previous_SegmentSet').
                        setCondition('Contact__c IN :contactIdSet').
                        addOrdering('Date_Of_Service_From__c', fflib_QueryFactory.SortOrder.DESCENDING).
                        toSOQL()
        );
    }

    //Sort records by descending Date_Of_Service_From__c
    public List<Claim_Information__c> selectExistingClaimsByUCKID(Set<String> Previous_ClaimIDSet) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        selectField(Claim_Information__c.PA_Approval_Dates__c).
                        selectField(Claim_Information__c.Date_Of_Service_From__c).
                        selectField(Claim_Information__c.Previous_Claim__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        setCondition('Primary_Claim_Number__c IN :Previous_ClaimIDSet').
                        addOrdering('Date_Of_Service_From__c', fflib_QueryFactory.SortOrder.DESCENDING).
                        toSOQL()
        );
    }

    //SOQL Order is not working. I believe it is because the records are being updated & inserted in the same transaction.
    //Sort record be descending Date_Of_Service_From__c
    public List<Claim_Information__c> selectExistingClaimsByContactDrugIdSet(Set<Id> contact_DrugIdSet) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        selectField(Claim_Information__c.PA_Approval_Dates__c).
                        selectField(Claim_Information__c.Date_Of_Service_From__c).
                        selectField(Claim_Information__c.Contact_Drug__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        setCondition('Contact_Drug__c IN :contact_DrugIdSet').
                        addOrdering('Date_Of_Service_From__c', fflib_QueryFactory.SortOrder.DESCENDING).
                        toSOQL()
        );
    }

    //SOQL Order is not working. I believe it is because the records are being updated & inserted in the same transaction.
    //Sort records by decending Date_Of_Service_From__c
    public List<Claim_Information__c> selectExistingClaimsByUniquekey(Set<String> claimNumberSet) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        selectField(Claim_Information__c.PA_Approval_Dates__c).
                        selectField(Claim_Information__c.Date_Of_Service_From__c).
                        selectField(Claim_Information__c.Previous_Claim__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        setCondition('Claim_Number__c IN :claimNumberSet').
                        addOrdering('Date_Of_Service_From__c', fflib_QueryFactory.SortOrder.DESCENDING).
                        toSOQL()
        );
    }

    //SOQL Order is not working. I believe it is because the records are being updated & inserted in the same transaction.
    //Sort records by decending Date_Of_Service_From__c
    public List<Claim_Information__c> selectExistingClaimsByCurrentClaimNumber(Set<String> currentClaimNumberSet) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        selectField(Claim_Information__c.PA_Approval_Dates__c).
                        selectField(Claim_Information__c.Date_Of_Service_From__c).
                        selectField(Claim_Information__c.Previous_Claim__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        setCondition('Current_Claim_Number__c IN :currentClaimNumberSet').
                        addOrdering('Date_Of_Service_From__c', fflib_QueryFactory.SortOrder.DESCENDING).
                        toSOQL()
        );
    }

    //SOQL Order is not working. I believe it is because the records are being updated & inserted in the same transaction.
    //Sort recordy be decending Date_Of_Service_From__c
    public List<Claim_Information__c> selectOriginalClaimsByUniquekey(Set<String> claimNumberSet) {

        return (List<Claim_Information__c>) Database.query(
                newQueryFactory().
                        selectField(Claim_Information__c.Id).
                        selectField(Claim_Information__c.OwnerId).
                        selectField(Claim_Information__c.Name).
                        //selectField(Claim_Information__c.Cardholder_s_Name__c).
                        selectField(Claim_Information__c.Contact__c).
                        selectField(Claim_Information__c.Primary_Claim_Number__c).
                        selectField(Claim_Information__c.Claim_Number__c).
                        selectField(Claim_Information__c.Current_Claim_Number__c).
                        selectField(Claim_Information__c.Previous_Segment__c).
                        //selectField(Claim_Information__c.Total_Drug_Cost__c).
                        selectField(Claim_Information__c.PA_Approval_Dates__c).
                        selectField(Claim_Information__c.Date_Of_Service_From__c).
                        selectField(Claim_Information__c.Contact_Drug__c).
                        selectField(Claim_Information__c.EOP_Date__c).
                        setCondition('Claim_Number__c IN :claimNumberSet').
                        addOrdering('Date_Of_Service_From__c', fflib_QueryFactory.SortOrder.DESCENDING).
                        toSOQL()
        );
    }
}