unpackaged/main/default/objects/Communication__c/Communication__c.object-meta.xml
<CustomObject>
    <description>This object exists as a detail record to the Member object, to track the different types of communications that are sent to a member.</description>
    <label>Communication</label>
    <nameField>
        <displayFormat>COMM-{000000}</displayFormat>
        <label>Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Communication__c/fields/Letter_ID__c.field-meta.xml
<CustomField>
    <fullName>Letter_ID__c</fullName>
    <label>Letter ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Welcome_Letter_Id__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Letter_Id__c</fullName>
    <description>Used to save the letter id from LOB</description>
    <label>Welcome Letter Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Welcome_Letter_Mailed_Date__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Letter_Mailed_Date__c</fullName>
    <description>The date when the LOB system returns that the welcome letter has been mailed.</description>
    <inlineHelpText>The date when the LOB system returns that the welcome letter has been mailed.</inlineHelpText>
    <label>Welcome Letter Mailed Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/webhookLOBEvents.cls
/**
 * @description       :
 * @author            : Garrett.Heathcote@PrudentRx.com
 * @group             :
 * @last modified on  : 05-15-2023
 * @last modified by  : Travis Sturdivant
 * Modifications Log
 * Ver   Date         Author                           Modification
 * 1.0   05-10-2022   Garrett Heathcote                Initial Version
 * 2.0   05-15-2023   Travis Sturdivant                Updating to use Communication__c object instead of Contact
 *
 **/
@RestResource(urlMapping='/api/Webhooks/LOBEvents/*')
global without sharing class webhookLOBEvents {
    @HttpPost
    global static void handleNotification() {
        RestRequest request = RestContext.request;
        
        String ltrId, responseCode,responseMessage;
        try{
            Blob b = request.requestBody;
            String requestString = RestContext.request.requestBody.toString();
            
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(requestString);
            String referenceId = (String) results.get('reference_id');
            //Currently only tracking mailed date so we would want to build this out later if we capture more events
            Map<String, Object> body = (Map<String, Object>) results.get('body');
            String templateId = (String) body.get('template_id');

            //TODO check secret 
//test 8e5c6936805d281dac5fd2144a24b67a9be088ec
//prod 394453af2b86e18eabfe53c509e33705bf707a21
            if(String.isBlank(referenceId))
            {
                String message = 'Reference Id is blank';
                responseCode = '422';
                responseMessage = '{success:false,event:"Empty Reference Id","message:"' + message + '"}';
            }
            else 
            {
                //Use the reference_id from LOB to find the Communication__c record in Salesforce 
                List<Communication__c> lstComm = [SELECT Id FROM Communication__c WHERE Letter_ID__c = :referenceId]; 
                if(lstComm.size() <= 0)
                {
                    String message = 'No communication found for Id:' + referenceId;
                    responseCode = '422';
                    responseMessage = '{success:false,event:"Bad Reference Id","message:"' + message + '"}';
                }
                else
                {          
                    String successMessage = '';
                    //Set the Mailed_Date__c on the Communication__c record to today's date
                    lstComm[0].Mailed_Date__c = system.today(); 
                    successMessage = 'Successfully updated Communication Mailed Date'; 

                    //Update the communication record
                    update lstComm;
                    
                    responseCode = '200';
                    responseMessage = '{success:true,event:"Update","message:"' + successMessage + '"}';
                }
            }
        }
        catch(Exception e)
        {
            System.debug('Rest Exception: ' + e.getMessage());            
            responseCode = '422';
            responseMessage = '{success:false,event:"Unknown","message:"' + e.getMessage() + '"}';      
        }
        
        RestResponse response = RestContext.response;
        if(response != null)
        {
            response.addHeader('Content-Type', 'application/json');
            response.responseBody = Blob.valueOf(responseMessage);
            response.statusCode = Integer.valueOf(responseCode);
        }
    }
   /* @HttpGet
    global static String handleGet() {
        String message = 'Nothing';
    /*    try{
            Contact c = [SELECT Id,Welcome_Letter_Id__c FROM Contact WHERE Id = '0032300000TbEr2AAF' LIMIT 1];// Welcome_Letter_Id__c =:ltrId];
            // lstContactsToCheck[0].Welcome_Letter_Id__c = 'Yay';
            //Contact c = new Contact();
            c.Welcome_Letter_Mailed_Date__c = system.now();
            c.Welcome_Letter_Id__c = 'Yay';
            update c;
        }
        catch(Exception e)
        {
            message = e.getMessage();
        }
       // return '{"message":"' + message + '"}';
    }*/
}

//https://dev1-lobevents.cs28.force.com/services/apexrest/api/Webhooks/LOBEvents/