unpackaged/main/default/objects/Account/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation</label>
    <referenceTo>Implementation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Medical_Drug_List__c.field-meta.xml
<CustomField>
    <fullName>Medical_Drug_List__c</fullName>
    <label>Medical Drug List</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRUDENTMED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Contact Drug</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Drug_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Name__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp; Contact_Drug__r.Drug_Name__c, Contact_Drug__r.Drug_Name__r.Name,&quot;_self&quot;)</formula>
    <label>Drug Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <formula>Contact.CSA__r.Go_Live_Date__c</formula>
    <label>Go Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Latest_PRx_Outreach_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Latest_PRx_Outreach_Attempt__c</fullName>
    <description>Last unsuccessful outreach date to the member. Format mm/dd/yyyy.</description>
    <inlineHelpText>Select the date of the latest telephonic outreach PRx made to either the MBR or HCP.</inlineHelpText>
    <label>Latest PRx Outreach Attempt</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Medical_Drug_List__c.field-meta.xml
<CustomField>
    <fullName>Medical_Drug_List__c</fullName>
    <formula>TEXT( Contact.CSA__r.Medical_Drug_List__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Medical Drug List</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Outreach_Comments__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Comments__c</fullName>
    <label>Outreach Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Outreach_Type__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Type__c</fullName>
    <description>Select who Aetna needs to make an outbound telephonic outreach to.</description>
    <inlineHelpText>Select who Aetna needs to make an outbound telephonic outreach to.</inlineHelpText>
    <label>Outreach Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MBR</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CSA__c.field-meta.xml
<CustomField>
    <fullName>CSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSA</label>
    <referenceTo>CSA__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CSA_Account__c.field-meta.xml
<CustomField>
    <fullName>CSA_Account__c</fullName>
    <description>A subdivision of suffix.  These subdivisions are designated by the purchaser &amp; Aetna for reporting, administrative, and financial needs (specifically to summarize/combine numbers).  An ACCOUNT will always be associated with at least one INDUSTRY.</description>
    <label>CSA Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CSA_Control__c.field-meta.xml
<CustomField>
    <fullName>CSA_Control__c</fullName>
    <description>A subdivision of a purchaser.  These subdivisions are designated by the purchaser and Aetna for reporting, administrative, and accounting needs
(specifically to summarize/combine suffixes).  A CONTROL will always be associated with at least one SUFFIX.  A CONTROL will always be associated with one and only one purchaser.</description>
    <label>CSA Control</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CSA_Suffix__c.field-meta.xml
<CustomField>
    <fullName>CSA_Suffix__c</fullName>
    <description>This is a subdivision of a control.  These subdivisions are designated  by the purchaser and Aetna for reporting administrative and accounting needs (specifically to summarize/combine accounts).  A SUFFIX will always be associated to one and only one
CONTROL.  A SUFFIX will always be associated with at least one ACCOUNT.</description>
    <label>CSA Suffix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Not Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <formula>CSA__r.Go_Live_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Medical_Drug_List__c.field-meta.xml
<CustomField>
    <fullName>Medical_Drug_List__c</fullName>
    <formula>TEXT(CSA__r.Medical_Drug_List__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Medical Drug List</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/Contact_Drug__c.object-meta.xml
<CustomObject>
    <label>Contact Drug</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Contact Drug Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact_Drug__c/fields/Drug_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Brand_Name__c</fullName>
    <description>Drug Brand Name</description>
    <formula>Drug_Name__r.Drug_Brand_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drug Brand Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>TEXT( Contact__r.Gender__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <formula>Contact__r.Go_Live_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/J_Code__c.field-meta.xml
<CustomField>
    <fullName>J_Code__c</fullName>
    <formula>Drug_Name__r.J_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>J - Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/CSA__c.object-meta.xml
<CustomObject>
    <label>CSA</label>
    <nameField>
        <displayFormat>CSA-{0000}</displayFormat>
        <label>CSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSA&#39;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CSA__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CSA&#39;s</relationshipLabel>
    <relationshipName>CSA_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/CSA_Account__c.field-meta.xml
<CustomField>
    <fullName>CSA_Account__c</fullName>
    <label>CSA Account</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/CSA_Control__c.field-meta.xml
<CustomField>
    <fullName>CSA_Control__c</fullName>
    <label>CSA Control</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/CSA_Number__c.field-meta.xml
<CustomField>
    <fullName>CSA_Number__c</fullName>
    <label>CSA_Number***</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/CSA_Suffix__c.field-meta.xml
<CustomField>
    <fullName>CSA_Suffix__c</fullName>
    <label>CSA Suffix</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation</label>
    <referenceTo>Implementation__c</referenceTo>
    <relationshipLabel>CSA&#39;s</relationshipLabel>
    <relationshipName>CSA_s</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/Medical_Drug_List__c.field-meta.xml
<CustomField>
    <fullName>Medical_Drug_List__c</fullName>
    <label>Medical Drug List</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRUDENTMED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Drug__c/Drug__c.object-meta.xml
<CustomObject>
    <description>The Main Drug Table</description>
    <label>Drug</label>
    <nameField>
        <label>Drug Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Drug__c/fields/Coding_Level__c.field-meta.xml
<CustomField>
    <fullName>Coding_Level__c</fullName>
    <label>Coding Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCPCS</fullName>
            </value>
            <value>
                <fullName>HCPCS + NDC</fullName>
            </value>
            <value>
                <fullName>HCPCS + DX</fullName>
            </value>
            <value>
                <fullName>ICD -10</fullName>
                <isActive>false</isActive>
                <label>ICD -10</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Drug__c/fields/Copay_Assistance_Available__c.field-meta.xml
<CustomField>
    <fullName>Copay_Assistance_Available__c</fullName>
    <label>CPA Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Drug__c/fields/Drug_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Brand_Name__c</fullName>
    <label>Drug Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Drug__c/fields/J_Code__c.field-meta.xml
<CustomField>
    <fullName>J_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Implementation__c/Implementation__c.object-meta.xml
<CustomObject>
    <label>Implementation</label>
    <nameField>
        <label>Implementation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Implementation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Implementations</relationshipLabel>
    <relationshipName>Implementations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Implementation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Implementations</relationshipLabel>
    <relationshipName>Implementations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Implementation__c/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <formula>Contract__r.Go_Live_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/SendLetterBatchTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-30-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class SendLetterBatchTest {

    private static Implementation__c implementationInstance;
    private static Contract contractInstance;
    private static Account accountInstance;

    @TestSetup
    public static void setupData(){

        List<CSA__c> csaList = new List<CSA__c>();
        Date goLiveDate = Date.newInstance(2023,1, 17);

        Account a = new Account();
        a.Name='Test Account';
        a.Go_Live_Date__c = Date.newInstance(2023,1, 17);
        insert a;

        //Adding the below section of code to create a new CSA record to resolve a test class issue
        system.debug('Setup Contracts');
        contractInstance = new Contract(
                Name = 'Model Office Test-Integration Contract',
                Go_Live_Date__c = goLiveDate,
                AccountId = a.Id
        );
        insert contractInstance;

        system.debug('Setup Implementation__c');
        implementationInstance =  new Implementation__c(
                Account__c = a.Id,
                Contract__c = contractInstance.Id
        );
        insert implementationInstance;
        
        CSA__c csaInstance = new CSA__c(
                Account__c = a.Id,
                Go_Live_Date__c = goLiveDate,
                CSA_Control__c = '865431',
                CSA_Suffix__c = '15',
                CSA_Account__c = '777',
                Medical_Drug_List__c = 'PRUDENTMED',
                Implementation__c = implementationInstance.Id
        );
        csaInstance.CSA_Number__c = SHA1UtilService.getBase64SHA1Hash(
                csaInstance.CSA_Control__c + '-' +
                        csaInstance.CSA_Suffix__c + '-' +
                        csaInstance.CSA_Account__c
        );
        csaList.add(csaInstance);

        insert csaList;

        Drug__c d = new Drug__c(); 
        d.Drug_Brand_Name__c = 'Test';
        d.Name = 'Test'; 
        d.Coding_Level__c = 'HCPCS'; 
        d.J_Code__c = '123456';
        d.Copay_Assistance_Available__c = 'Yes';
        insert d; 

        List<Contact> lstContactsTobeCreated = new List<Contact>(); 

        Contact c = new Contact();
        c.FirstName='TestHello';
        c.LastName = 'ContactHello';
        c.Birthdate= Date.newInstance(1990,1, 11);
        c.Gender__c = 'Male';
        c.MailingStreet = 'address line 1\n addressline2';
        c.MailingCity = 'Raleigh';
        c.MailingState = 'NC';
        c.MailingPostalCode = '27616';
        c.AccountId = a.Id;
        c.CSA__c = csaList[0].Id;
        lstContactsTobeCreated.add(c);

        Contact c1 = new Contact();
        c1.FirstName='Test';
        c1.LastName = 'TestHello';
        c1.Birthdate= Date.newInstance(1986,10, 18);
        c1.Gender__c = 'Female';
        c1.MailingStreet = 'address line 1\n addressline2';
        c1.MailingCity = 'Charleston';
        c1.MailingState = 'SC';
        c1.MailingPostalCode = '29420';
        c1.AccountId = a.Id;
        c1.CSA__c = csaList[0].Id;
        lstContactsTobeCreated.add(c1);

        Contact c2 = new Contact();
        c2.FirstName='TestThree';
        c2.LastName = 'Three';
        c2.Birthdate= Date.newInstance(1996,10, 18);
        c2.Gender__c = 'Male';
        c2.MailingStreet = 'address line 1\n addressline2';
        c2.MailingCity = 'Charleston';
        c2.MailingState = 'SC';
        c2.MailingPostalCode = '29420';
        c2.AccountId = a.Id;
        c2.CSA__c = csaList[0].Id;
        lstContactsTobeCreated.add(c2);

        Contact c3 = new Contact();
        c3.FirstName='TestFour';
        c3.LastName = 'Three';
        c3.Birthdate= Date.newInstance(1996,10, 18);
        c3.Gender__c = 'Male';
        c3.MailingStreet = 'address line 1\n addressline2';
        c3.MailingCity = 'Charleston';
        c3.MailingState = 'SC';
        c3.MailingPostalCode = '29420';
        c3.AccountId = a.Id;
        c3.CSA__c = csaList[0].Id;
        lstContactsTobeCreated.add(c3);        

        insert lstContactsTobeCreated; 

        List<Case> lstCasesToAdd = new List<Case>(); 

        Case case1 = new Case(); 
        case1.RecordTypeId = '0125e000000mHQ7AAM'; 
        case1.ContactId = c.Id; 
        case1.Outreach_Type__c = 'Both'; 
        case1.Outreach_Comments__c = 'TEST'; 
        case1.Status = 'Transfer to Health Plan'; 
        case1.Latest_PRx_Outreach_Attempt__c = Date.today().addDays(-1); 
        lstCasesToAdd.add(case1); 

        Case case2 = new Case(); 
        case2.RecordTypeId = '0125e000000mHQ7AAM'; 
        case2.ContactId = c1.Id; 
        case2.Outreach_Type__c = 'Both'; 
        case2.Outreach_Comments__c = 'TEST'; 
        case2.Status = 'Transfer to Health Plan'; 
        case2.Latest_PRx_Outreach_Attempt__c = Date.today().addDays(-7); 
        lstCasesToAdd.add(case2); 

        Case case3 = new Case(); 
        case3.RecordTypeId = '0125e000000mHQ7AAM'; 
        case3.ContactId = c2.Id; 
        case3.Outreach_Type__c = 'Both'; 
        case3.Outreach_Comments__c = 'TEST'; 
        case3.Status = 'Transfer to Health Plan'; 
        case3.Latest_PRx_Outreach_Attempt__c = Date.today(); 
        lstCasesToAdd.add(case3); 

        Case case4 = new Case(); 
        case4.RecordTypeId = '0125e000000mHQ7AAM'; 
        case4.ContactId = c3.Id; 
        case4.Outreach_Type__c = 'Both'; 
        case4.Outreach_Comments__c = 'TEST'; 
        case4.Status = 'Transfer to Health Plan'; 
        case4.Latest_PRx_Outreach_Attempt__c = Date.today().addDays(-1); 
        lstCasesToAdd.add(case4); 

        insert(lstCasesToAdd); 

        Contact_Drug__c cd = new Contact_Drug__c(); 
        cd.Drug_Name__c = d.Id; 
        cd.Copay_Enrollment_Status__c = 'Pending'; 
        cd.Related_Case__c = case2.Id; 
        insert cd; 

    }

    @isTest
    public static void testFinalNoticeBatch() {
        Test.startTest(); 
        Test.setMock(HttpCalloutMock.class, new LetterServiceMock('testSendFinalNoticeSuccess'));
        SendLetterBatch batch = new SendLetterBatch('Send Final Notice', null); 
        try {
            Database.executeBatch(batch);
        } catch (Exception ex) {
            System.assertEquals(ex.getMessage(), 'You have uncommitted work pending. Please commit or rollback before calling out');
        }
        Test.stopTest(); 
    }

    @isTest
    public static void testFinalNoticeWithdate() {
        Test.startTest(); 
        Test.setMock(HttpCalloutMock.class, new LetterServiceMock('testSendFinalNoticeSuccess'));
        SendLetterBatch batch = new SendLetterBatch('Send Final Notice', Date.today().format()); 
        Database.executeBatch(batch);
        Test.stopTest(); 
    }

    @isTest 
    public static void testFinalNoticeNoCasesFound() {
        Test.startTest(); 
        Test.setMock(HttpCalloutMock.class, new LetterServiceMock('testSendFinalNoticeSuccess'));
        SendLetterBatch batch = new SendLetterBatch('Send Final Notice', date.newInstance(2022, 2, 10).format()); 
        Database.executeBatch(batch);
        Test.stopTest(); 
    }

    @isTest
    public static void testWelcomeLetterBatch() {
        Test.startTest(); 
        Test.setMock(HttpCalloutMock.class, new LetterServiceMock('testWelcomeLetterSuccess'));
        SendLetterBatch batch = new SendLetterBatch('Send Welcome', '');
        Database.executeBatch(batch); 
        Test.stopTest(); 
    }
}