unpackaged/main/default/objects/Account/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Contact Drug</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Drug_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Name__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp; Contact_Drug__r.Drug_Name__c, Contact_Drug__r.Drug_Name__r.Name,&quot;_self&quot;)</formula>
    <label>Drug Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EOP_Date__c.field-meta.xml
<CustomField>
    <fullName>EOP_Date__c</fullName>
    <label>EOP Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <formula>Contact.CSA__r.Go_Live_Date__c</formula>
    <label>Go Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Latest_PRx_Outreach_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Latest_PRx_Outreach_Attempt__c</fullName>
    <description>Last unsuccessful outreach date to the member. Format mm/dd/yyyy.</description>
    <inlineHelpText>Select the date of the latest telephonic outreach PRx made to either the MBR or HCP.</inlineHelpText>
    <label>Latest PRx Outreach Attempt</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Outreach_Comments__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Comments__c</fullName>
    <label>Outreach Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Outreach_Type__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Type__c</fullName>
    <description>Select who Aetna needs to make an outbound telephonic outreach to.</description>
    <inlineHelpText>Select who Aetna needs to make an outbound telephonic outreach to.</inlineHelpText>
    <label>Outreach Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MBR</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/Claim_Information__c.object-meta.xml
<CustomObject>
    <label>Claim Information</label>
    <nameField>
        <displayFormat>Claim-{0000}</displayFormat>
        <label>Claims Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Claim_Information__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/CPA_Funds_Paid__c.field-meta.xml
<CustomField>
    <fullName>CPA_Funds_Paid__c</fullName>
    <label>CPA Funds Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/CPA_Indicator__c.field-meta.xml
<CustomField>
    <fullName>CPA_Indicator__c</fullName>
    <label>CPA Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opt-in - Paid in full</fullName>
            </value>
            <value>
                <fullName>Opt-in - Partial payment</fullName>
            </value>
            <value>
                <fullName>Opt-in - Funds exhausted</fullName>
            </value>
            <value>
                <fullName>Opt-in - CPA not available</fullName>
            </value>
            <value>
                <fullName>Opt-in - Reimbursement not Confirmed</fullName>
            </value>
            <value>
                <fullName>Opt-out - Refused</fullName>
            </value>
            <value>
                <fullName>Opt-out - Member not Enrolled</fullName>
            </value>
            <value>
                <fullName>Opt-In: CPA Available</fullName>
                <isActive>false</isActive>
                <label>Opt-In: CPA Available</label>
            </value>
            <value>
                <fullName>Opt-Out: MBR Refused</fullName>
                <isActive>false</isActive>
                <label>Opt-Out: MBR Refused</label>
            </value>
            <value>
                <fullName>Opt-Out: MBR UTC</fullName>
                <isActive>false</isActive>
                <label>Opt-Out: MBR UTC</label>
            </value>
            <value>
                <fullName>Opt-out - CPA not confirmed</fullName>
                <isActive>false</isActive>
                <label>Opt-out - CPA not confirmed</label>
            </value>
            <value>
                <fullName>Opt-out - Reimbursement not Confirmed</fullName>
                <isActive>false</isActive>
                <label>Opt-out - Reimbursement not Confirmed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Drug_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Brand_Name__c</fullName>
    <formula>Drug__r.Drug_Brand_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drug Brand Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/EOP_Date__c.field-meta.xml
<CustomField>
    <fullName>EOP_Date__c</fullName>
    <label>EOP Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Not Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <formula>CSA__r.Go_Live_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/Contact_Drug__c.object-meta.xml
<CustomObject>
    <label>Contact Drug</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Contact Drug Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact_Drug__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Copay_Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Copay_Enrollment_Status__c</fullName>
    <label>CPA Enrollment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not on File</fullName>
                <default>true</default>
                <label>Not on File</label>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>On File</fullName>
            </value>
            <value>
                <fullName>Refused</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Drug_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Brand_Name__c</fullName>
    <description>Drug Brand Name</description>
    <formula>Drug_Name__r.Drug_Brand_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drug Brand Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Drug_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug Name</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>TEXT( Contact__r.Gender__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <formula>Contact__r.Go_Live_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/J_Code__c.field-meta.xml
<CustomField>
    <fullName>J_Code__c</fullName>
    <formula>Drug_Name__r.J_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>J - Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Drug__c/Drug__c.object-meta.xml
<CustomObject>
    <description>The Main Drug Table</description>
    <label>Drug</label>
    <nameField>
        <label>Drug Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Drug__c/fields/Coding_Level__c.field-meta.xml
<CustomField>
    <fullName>Coding_Level__c</fullName>
    <label>Coding Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCPCS</fullName>
            </value>
            <value>
                <fullName>HCPCS + NDC</fullName>
            </value>
            <value>
                <fullName>HCPCS + DX</fullName>
            </value>
            <value>
                <fullName>ICD -10</fullName>
                <isActive>false</isActive>
                <label>ICD -10</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Drug__c/fields/Copay_Assistance_Available__c.field-meta.xml
<CustomField>
    <fullName>Copay_Assistance_Available__c</fullName>
    <label>CPA Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Drug__c/fields/Drug_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Drug_Brand_Name__c</fullName>
    <label>Drug Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Drug__c/fields/J_Code__c.field-meta.xml
<CustomField>
    <fullName>J_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SendFaxBatchTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-30-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class SendFaxBatchTest {
    @TestSetup
    public static void setupData() {
        Account a = new Account();
        a.Name='Test Account';
        a.Go_Live_Date__c = Date.newInstance(2023,1, 17);
        insert a;

        Drug__c d = new Drug__c(); 
        d.Drug_Brand_Name__c = 'Test';
        d.Name = 'Test'; 
        d.Coding_Level__c = 'HCPCS'; 
        d.J_Code__c = '123456';
        d.Copay_Assistance_Available__c = 'Yes';
        insert d; 

        List<Contact> lstContactsTobeCreated = new List<Contact>(); 

        Contact c = new Contact();
        c.FirstName='TestHello';
        c.LastName = 'ContactHello';
        c.Birthdate= Date.newInstance(1990,1, 11);
        c.Gender__c = 'Male';
        c.MailingStreet = 'address line 1\n addressline2';
        c.MailingCity = 'Raleigh';
        c.MailingState = 'NC';
        c.MailingPostalCode = '27616';
        c.AccountId = a.Id;
        lstContactsTobeCreated.add(c);

        Contact c1 = new Contact();
        c1.FirstName='Test';
        c1.LastName = 'TestHello';
        c1.Birthdate= Date.newInstance(1986,10, 18);
        c1.Gender__c = 'Female';
        c1.MailingStreet = 'address line 1\n addressline2';
        c1.MailingCity = 'Charleston';
        c1.MailingState = 'SC';
        c1.MailingPostalCode = '29420';
        c1.AccountId = a.Id;
        lstContactsTobeCreated.add(c1);

        Contact c2 = new Contact();
        c2.FirstName='TestThree';
        c2.LastName = 'Three';
        c2.Birthdate= Date.newInstance(1996,10, 18);
        c2.Gender__c = 'Male';
        c2.MailingStreet = 'address line 1\n addressline2';
        c2.MailingCity = 'Charleston';
        c2.MailingState = 'SC';
        c2.MailingPostalCode = '29420';
        c2.AccountId = a.Id;
        lstContactsTobeCreated.add(c2);

        Contact c3 = new Contact();
        c3.FirstName='TestFour';
        c3.LastName = 'Three';
        c3.Birthdate= Date.newInstance(1996,10, 18);
        c3.Gender__c = 'Male';
        c3.MailingStreet = 'address line 1\n addressline2';
        c3.MailingCity = 'Charleston';
        c3.MailingState = 'SC';
        c3.MailingPostalCode = '29420';
        c3.AccountId = a.Id;
        lstContactsTobeCreated.add(c3);        

        insert lstContactsTobeCreated; 

        List<Case> lstCasesToAdd = new List<Case>(); 

        Case case1 = new Case(); 
        case1.RecordTypeId = '0125e000000mHQ8AAM'; 
        case1.ContactId = c.Id; 
        case1.Outreach_Type__c = 'Both'; 
        case1.Outreach_Comments__c = 'UPDATE LATER'; 
        case1.Status = 'Verify Fax Number'; 
        case1.Latest_PRx_Outreach_Attempt__c = Date.today().addDays(-1); 
        lstCasesToAdd.add(case1); 

        Case case2 = new Case(); 
        case2.RecordTypeId = '0125e000000mHQ8AAM'; 
        case2.ContactId = c1.Id; 
        case2.Outreach_Type__c = 'Both'; 
        case2.Outreach_Comments__c = 'TEST'; 
        case2.Status = 'Verify Fax Number'; 
        case2.Latest_PRx_Outreach_Attempt__c = Date.today().addDays(-7); 
        lstCasesToAdd.add(case2); 

        Case case3 = new Case(); 
        case3.RecordTypeId = '0125e000000mHQ8AAM'; 
        case3.ContactId = c2.Id; 
        case3.Outreach_Type__c = 'Both'; 
        case3.Outreach_Comments__c = 'TEST'; 
        case3.Status = 'Outreach Complete'; 
        case3.Latest_PRx_Outreach_Attempt__c = Date.today(); 
        lstCasesToAdd.add(case3); 

        Case case4 = new Case(); 
        case4.RecordTypeId = '0125e000000mHQ8AAM'; 
        case4.ContactId = c3.Id; 
        case4.Outreach_Type__c = 'Both'; 
        case4.Outreach_Comments__c = 'TEST'; 
        case4.Status = 'Transfer to Health Plan'; 
        case4.Latest_PRx_Outreach_Attempt__c = Date.today().addDays(-1); 
        lstCasesToAdd.add(case4); 

        insert(lstCasesToAdd); 

        Contact_Drug__c cd = new Contact_Drug__c(); 
        cd.Drug_Name__c = d.Id; 
        cd.Copay_Enrollment_Status__c = 'Pending'; 
        cd.Related_Case__c = case2.Id; 
        insert cd; 

        List<Claim_Information__c> lstClaimsToAdd = new List<Claim_Information__c>(); 

        Claim_Information__c claim1 = new Claim_Information__c(); 
        claim1.Contact__c = c.Id; 
        claim1.EOP_Date__c = date.today().addDays(-75); 
        claim1.Drug__c = d.Id; 
        claim1.Contact_Drug__c = cd.Id; 
        claim1.CPA_Indicator__c = 'Opt-in - CPA not available';
        claim1.CPA_Funds_Paid__c = 30;
        lstClaimsToAdd.add(claim1);

        Claim_Information__c claim2 = new Claim_Information__c(); 
        claim2.Contact__c = c2.Id; 
        claim2.EOP_Date__c = date.today().addDays(-55);
        claim2.Drug__c = d.Id; 
        claim2.Contact_Drug__c = cd.Id; 
        claim2.CPA_Indicator__c = 'Opt-in - CPA not available';
        claim2.CPA_Funds_Paid__c = 30;
        lstClaimsToAdd.add(claim2); 

        insert lstClaimsToAdd; 
        
        // Update Cases with Claim Information values 
        List<Case> lstCasesToUpdate = new List<Case>(); 
        
        case1.Claim_Information__c = claim1.Id; 
        lstCasesToUpdate.add(case1); 

        case2.Claim_Information__c = claim2.Id; 
        lstCasesToUpdate.add(case2); 

        update lstCasesToUpdate; 
    }

    @isTest
    public static void testFinalNoticeFaxSuccess(){
        Test.startTest(); 
        SendFaxBatch batch = new SendFaxBatch('Final Notice'); 
        Database.executeBatch(batch);
        Test.stopTest(); 
    }

    @isTest
    public static void testFinalNoticeFaxNoRecords() {
        //Update status of case1 to make it so no valid records are found
        Case caseToUpdate = [SELECT Id, Status, HCP_Enrollment_Outreach__c FROM Case WHERE Outreach_Comments__c = 'UPDATE LATER' LIMIT 1];
        caseToUpdate.Status = 'Outreach Completed'; 
        caseToUpdate.HCP_Enrollment_Outreach__c = 'Outreach Complete';
        update caseToUpdate; 

        Test.startTest(); 
        SendFaxBatch batch = new SendFaxBatch('Final Notice'); 
        Database.executeBatch(batch);
        Test.stopTest(); 
    }
}