unpackaged/main/default/objects/Case/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Daily_Claim__c.field-meta.xml
<CustomField>
    <fullName>Daily_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Claim</label>
    <referenceTo>Daily_Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Historical_Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Historical_Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Historical Prior Auth</label>
    <referenceTo>Historical_Prior_Auth__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prior Auth</label>
    <referenceTo>Prior_Auth__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/Claim_Information__c.object-meta.xml
<CustomObject>
    <label>Claim Information</label>
    <nameField>
        <displayFormat>Claim-{0000}</displayFormat>
        <label>Claims Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Daily_Claim__c/Daily_Claim__c.object-meta.xml
<CustomObject>
    <label>Daily Claim</label>
    <nameField>
        <displayFormat>DC-{0000000}</displayFormat>
        <label>Daily Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Daily_Claim__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Daily Claims</relationshipLabel>
    <relationshipName>Daily_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <description>If HCPCS does not exist on Drug object, then don’t process record and set:
     - Status [NEW FIELD] to “Error”
     - Error Log [NEW FIELD] to “HCPCS Mismatch.” Dependent and connected to the Status field.</description>
    <label>Error Log</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>HCPCS Mismatch</fullName>
            </value>
            <value>
                <fullName>CSA Mismatch</fullName>
            </value>
            <value>
                <fullName>Previous segment not found</fullName>
            </value>
            <value>
                <fullName>Unable to create record due to duplicate.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Error_Log__c/fields/Daily_Claim__c.field-meta.xml
<CustomField>
    <fullName>Daily_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Claim</label>
    <referenceTo>Daily_Claim__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Historical_Claim__c.field-meta.xml
<CustomField>
    <fullName>Historical_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Historical Claim record.</description>
    <label>Historical Claim</label>
    <referenceTo>Historical_Claim__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Historical_Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Historical_Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Historical Prior Auth record.</description>
    <label>Historical Prior Auth</label>
    <referenceTo>Historical_Prior_Auth__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Prior Auth record.</description>
    <label>Prior Auth</label>
    <referenceTo>Prior_Auth__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Claim__c/Historical_Claim__c.object-meta.xml
<CustomObject>
    <label>Historical Claim</label>
    <nameField>
        <displayFormat>HC-{0000000}</displayFormat>
        <label>Historical Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historical_Claim__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Historical Claims</relationshipLabel>
    <relationshipName>Historical_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Prior_Auth__c/Historical_Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Historical Prior Auth</label>
    <nameField>
        <displayFormat>HPA-{0000000}</displayFormat>
        <label>Historical Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historical_Prior_Auth__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Historical Prior Auth</relationshipLabel>
    <relationshipName>Historical_Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prior_Auth__c/Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Prior Auth</label>
    <nameField>
        <displayFormat>DPA-{0000000}</displayFormat>
        <label>Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prior_Auth__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Prior Auth</relationshipLabel>
    <relationshipName>Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prior_Auth__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCPCS Mismatch</fullName>
            </value>
            <value>
                <fullName>CSA Mismatch</fullName>
            </value>
            <value>
                <fullName>Unable to create record due to duplicate.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ErrorLogSelector.cls
/**
 * @author Ricardy Banks
 * @date 02/15/2023
 * @description This class is used to select data from the ErrorLog object. It's the only place that case object queries
 * should be made
 */

//We extend the fflib_SObjectSelector class to gain access to its many useful prebuilt methods
//We extend the Task_Selector_Interface to force it to implement a particular set of methods to help with abstraction
//in the Task_Service_Impl class
public inherited sharing class ErrorLogSelector extends fflib_SObjectSelector
{

    public ErrorLogSelector(){
        super(false, true, true, false);
    }
    /*
    public static ICasesSelector newInstance()
    {
        return (ICasesSelector) PMd_Application.Selector.newInstance(Case.SObjectType);
    }
    */
    //This sets the base fields that you will ALWAYS have in your queries when calling this selector class
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
                Error_Log__c.Id,
                Error_Log__c.Name,
                Error_Log__c.Error_Message__c,
                Error_Log__c.Daily_Claim__c,
                Error_Log__c.Historical_Claim__c,
                Error_Log__c.Historical_Prior_Auth__c,
                Error_Log__c.Prior_Auth__c,
                Error_Log__c.CreatedDate
        };
    }

    //This will return your object type for this selector, useful in abstractions
    public Schema.SObjectType getSObjectType(){
        return Error_Log__c.SObjectType;
    }

    //This method calls the fflib_SObjectSelector classes selectSObjectsById method and returns a list
    //of cases from the caseIds you sent in with the default fields declared in the getSObjectFieldList method above
    public List<Error_Log__c> selectById(Set<Id> errorLogIds){
        return (List<Error_Log__c>) selectSObjectsById(errorLogIds);
    }

    //This uses the fflib_SObjectSelector class's QueryFactory inner class to create a custom query with
    //extra fields selected and conditions set
    public Database.QueryLocator selectErrorLogsByCreatedDate(Date createdDate){

        System.debug('selectErrorLogsByDailyClaimId = ' + newQueryFactory().
                setCondition('CreatedDate = TODAY').
                toSOQL()
        );

        return Database.getQueryLocator(
                newQueryFactory().
                        setCondition('CreatedDate = TODAY').
                        toSOQL()
        );
    }
/*
    //This uses the fflib_SObjectSelector class's QueryFactory inner class to create a custom query with
    //extra fields selected and conditions set
    public Database.QueryLocator selectErrorLogsByDailyClaimId(Set<Id> dailyClaimIds){

        System.debug('selectErrorLogsByDailyClaimId = ' + newQueryFactory().
                setCondition('Id IN :dailyClaimIds').
                toSOQL()
        );

        return Database.getQueryLocator(
                newQueryFactory().
                        setCondition('Claim_Information__c IN :dailyClaimIds').
                        toSOQL()
        );
    }
*/
}