unpackaged/main/default/objects/Case/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Contact Drug</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Daily_Claim__c.field-meta.xml
<CustomField>
    <fullName>Daily_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Claim</label>
    <referenceTo>Daily_Claim__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Historical_Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Historical_Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Historical Prior Auth</label>
    <referenceTo>Historical_Prior_Auth__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prior Auth</label>
    <referenceTo>Prior_Auth__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/Claim_Information__c.object-meta.xml
<CustomObject>
    <label>Claim Information</label>
    <nameField>
        <displayFormat>Claim-{0000}</displayFormat>
        <label>Claims Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Claim_Information__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Claim_Information__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Claims Information</relationshipLabel>
    <relationshipName>Claims_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/Contact_Drug__c.object-meta.xml
<CustomObject>
    <label>Contact Drug</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Contact Drug Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact_Drug__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Daily_Claim__c.field-meta.xml
<CustomField>
    <fullName>Daily_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Daily Claim</description>
    <label>Daily Claim</label>
    <referenceTo>Daily_Claim__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Historical_Claim__c.field-meta.xml
<CustomField>
    <fullName>Historical_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Historical Claim</description>
    <label>Historical Claim</label>
    <referenceTo>Historical_Claim__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Historical_Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Historical_Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Historical Prior Auth</label>
    <referenceTo>Historical_Prior_Auth__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact_Drug__c/fields/Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prior Auth</label>
    <referenceTo>Prior_Auth__c</referenceTo>
    <relationshipLabel>Contact Drugs</relationshipLabel>
    <relationshipName>Contact_Drugs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/Daily_Claim__c.object-meta.xml
<CustomObject>
    <label>Daily Claim</label>
    <nameField>
        <displayFormat>DC-{0000000}</displayFormat>
        <label>Daily Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Daily_Claim__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Daily Claims</relationshipLabel>
    <relationshipName>Daily_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Daily Claims</relationshipLabel>
    <relationshipName>Daily_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Error_Log__c/fields/Daily_Claim__c.field-meta.xml
<CustomField>
    <fullName>Daily_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Claim</label>
    <referenceTo>Daily_Claim__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Historical_Claim__c.field-meta.xml
<CustomField>
    <fullName>Historical_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Historical Claim record.</description>
    <label>Historical Claim</label>
    <referenceTo>Historical_Claim__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Historical_Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Historical_Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Historical Prior Auth record.</description>
    <label>Historical Prior Auth</label>
    <referenceTo>Historical_Prior_Auth__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Prior Auth record.</description>
    <label>Prior Auth</label>
    <referenceTo>Prior_Auth__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Claim__c/Historical_Claim__c.object-meta.xml
<CustomObject>
    <label>Historical Claim</label>
    <nameField>
        <displayFormat>HC-{0000000}</displayFormat>
        <label>Historical Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historical_Claim__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Historical Claims</relationshipLabel>
    <relationshipName>Historical_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Prior_Auth__c/Historical_Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Historical Prior Auth</label>
    <nameField>
        <displayFormat>HPA-{0000000}</displayFormat>
        <label>Historical Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historical_Prior_Auth__c/fields/Claim_Information__c.field-meta.xml
<CustomField>
    <fullName>Claim_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Information</label>
    <referenceTo>Claim_Information__c</referenceTo>
    <relationshipLabel>Historical Prior Auth</relationshipLabel>
    <relationshipName>Historical_Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Prior_Auth__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Historical Prior Auth</relationshipLabel>
    <relationshipName>Historical_Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NDC__c/NDC__c.object-meta.xml
<CustomObject>
    <description>Drugs are identified and reported using a unique, three-segment number called the National Drug Code (NDC) which serves as the FDA’s identifier for drugs.</description>
    <label>NDC</label>
    <nameField>
        <label>NDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NDC__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>NDCs</relationshipLabel>
    <relationshipName>NDCs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prior_Auth__c/Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Prior Auth</label>
    <nameField>
        <displayFormat>DPA-{0000000}</displayFormat>
        <label>Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prior_Auth__c/fields/Contact_Drug__c.field-meta.xml
<CustomField>
    <fullName>Contact_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Drug</label>
    <referenceTo>Contact_Drug__c</referenceTo>
    <relationshipLabel>Prior Auth</relationshipLabel>
    <relationshipName>Prior_Auth</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prior_Auth__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp; Contact_Drug__r.Drug_Name__c, Drug_Label_Name__c,&quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drug</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PMd_Application.cls
/**
 * @description       : 
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             : 
 * @last modified on  : 08-06-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log 
 * Ver   Date         Author                           Modification
 * 1.0   08-06-2021   Ricardy Banks                    Initial Version
 * 
 */

public class PMd_Application {

	// Configure and create the UnitOfWorkFactory for this Application
	public static final fflib_Application.UnitOfWorkFactory UnitOfWork =
			new fflib_Application.UnitOfWorkFactory(
					new List<SObjectType> {
							Daily_Claim__c.SObjectType,
							Historical_Claim__c.SObjectType,
							Prior_Auth__c.SObjectType,
							Historical_Prior_Auth__c.SObjectType,
							Member_Demographic__c..SObjectType,
							Provider_Demographic__c.SObjectType,
							Account.SObjectType,
							Contact.SObjectType,
							Contact_Drug__c.SObjectType,
							Claim_Information__c.SObjectType,
							Case.SObjectType,
							CSA__c.SObjectType,
							Task.SObjectType
							//Error_Log__c.SObjectType
					}
							//Error_Log__c.SObjectType}
			);

	// Configure and create the ServiceFactory for this Application
	public static final fflib_Application.ServiceFactory Service =
			new fflib_Application.ServiceFactory(
					new Map<Type, Type> {
							IDaily_ClaimsService.class => Daily_ClaimsServiceImpl.class,
							IHistorical_ClaimsService.class => Historical_ClaimsServiceImpl.class,
							IRestAPIService.class => RestAPIsServiceceImpl.class,
							ISHA1UtilService.class => SHA1UtilServiceImpl.class,
							IFormatterUtilService.class => FormatterUtilServiceImpl.class,
							ICaseService.class => CaseServiceImpl.class
					});


	// Configure and create the DomainFactory for this Application
	public static final fflib_Application.DomainFactory Domain =
			new fflib_Application.DomainFactory(
					PMd_Application.Selector,
					new Map<SObjectType, Type> {
							Daily_Claim__c.SObjectType => Daily_Claims.Constructor.class,
							Historical_Claim__c.SObjectType => Historical_Claims.Constructor.class,
							Prior_Auth__c.SObjectType => Prior_Auth.Constructor.class,
							Historical_Prior_Auth__c.SObjectType => Historical_Prior_Auth.Constructor.class,
							Member_Demographic__c.SObjectType => Member_Demo.Constructor.class,
							Provider_Demographic__c.SObjectType => Provider_Demographic.Constructor.class,
							Contact_Drug__c.SObjectType => Contact_Drugs.Constructor.class,
							Claim_Information__c.SObjectType => Claim_Informations.Constructor.class,
							Case.SObjectType => Cases.Constructor.class,
							Contact.SObjectType => Contacts.Constructor.class,
							CSA__c.SObjectType => CSAs.Constructor.class
							//Error_Log__c.SObjectType => ErrorLog.Constructor.class

					});

	// Configure and create the SelectorFactory for this Application
	public static final fflib_Application.SelectorFactory Selector =
			new fflib_Application.SelectorFactory(
					new Map<SObjectType, Type> {
							Daily_Claim__c.SObjectType => Daily_ClaimsSelector.class,
							Historical_Claim__c.SObjectType => Historical_ClaimsSelector.class,
							Prior_Auth__c.SObjectType => Prior_AuthSelector.class,
							Historical_Prior_Auth__c.SObjectType => Historical_Prior_AuthSelector.class,
							Account.SObjectType => AccountsSelector.class,
							Contact.SObjectType => ContactsSelector.class,
							Contact_Drug__c.SObjectType => Contact_DrugsSelector.class,
							Claim_Information__c.SObjectType => Claim_InformationsSelector.class,
							Case.SObjectType => CasesSelector.class,
							CSA__c.SObjectType => CSAsSelector.class,
							Drug__c.SObjectType => DrugsSelector.class,
							NDC__c.SObjectType => NDCsSelector.class,
							Error_Log__c.SObjectType => ErrorLogSelector.class
							//User.SObjectType => UsersSelector.class
							//Task.SObjectType => Task_Selector.class
					});
}