unpackaged/main/default/objects/Contact/fields/CSA__c.field-meta.xml
<CustomField>
    <fullName>CSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSA</label>
    <referenceTo>CSA__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/CSA__c.object-meta.xml
<CustomObject>
    <label>CSA</label>
    <nameField>
        <displayFormat>CSA-{0000}</displayFormat>
        <label>CSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSA&#39;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Daily_Claim__c/Daily_Claim__c.object-meta.xml
<CustomObject>
    <label>Daily Claim</label>
    <nameField>
        <displayFormat>DC-{0000000}</displayFormat>
        <label>Daily Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historical_Claim__c/Historical_Claim__c.object-meta.xml
<CustomObject>
    <label>Historical Claim</label>
    <nameField>
        <displayFormat>HC-{0000000}</displayFormat>
        <label>Historical Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historical_Prior_Auth__c/Historical_Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Historical Prior Auth</label>
    <nameField>
        <displayFormat>HPA-{0000000}</displayFormat>
        <label>Historical Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prior_Auth__c/Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Prior Auth</label>
    <nameField>
        <displayFormat>DPA-{0000000}</displayFormat>
        <label>Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/IContacts.cls
/**
 * @description       :
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             :
 * @last modified on  : 08-08-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log
 * Ver   Date         Author                           Modification
 * 1.0   08-06-2021   Ricardy Banks					   Initial Version
 *
 **/

public interface IContacts extends fflib_ISObjects {
    List<Contact> getContacts();
    void setDescription(String description);
    Map<Id, Contact> process(List<Daily_Claim__c> dailyClaims, Map<String, CSA__c> csasByCSA_Number, fflib_ISObjectUnitOfWork unitOfWork);
    Map<Id, Contact> process(List<Historical_Claim__c> historicalClaims, fflib_ISObjectUnitOfWork unitOfWork);
    Map<Id, Contact> process(List<Prior_Auth__c> priorAuth, fflib_ISObjectUnitOfWork unitOfWork);
    Map<Id, Contact> process(List<Historical_Prior_Auth__c> historicalPriorAuthClaims, fflib_ISObjectUnitOfWork unitOfWork);
    Map<Id, Contact> mapContactsByDailyClaimId(List<Contact> existingContactList, List<Daily_Claim__c> dailyClaimsList);
    Map<Id, Contact> getExistingContactsByDailyClaimId(List<Daily_Claim__c> dailyClaimsList);
    Map<Id, Contact> getExistingContactsByHistoricalClaimId(List<Historical_Claim__c> historicalClaimsList);
    Map<Id, Contact> getExistingContactsByPriorAuthId(List<Prior_Auth__c> priorAuthsList);
    Map<Id, Contact> getExistingContactsByHistoricalPriorAuthId(List<Historical_Prior_Auth__c> historicalPriorAuthsList);
}