unpackaged/main/default/objects/CSA__c/CSA__c.object-meta.xml
<CustomObject>
    <label>CSA</label>
    <nameField>
        <displayFormat>CSA-{0000}</displayFormat>
        <label>CSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSA&#39;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CSA__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CSA&#39;s</relationshipLabel>
    <relationshipName>CSA_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/CSA_Account__c.field-meta.xml
<CustomField>
    <fullName>CSA_Account__c</fullName>
    <label>CSA Account</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/CSA_Control__c.field-meta.xml
<CustomField>
    <fullName>CSA_Control__c</fullName>
    <label>CSA Control</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/CSA_Number__c.field-meta.xml
<CustomField>
    <fullName>CSA_Number__c</fullName>
    <label>CSA_Number***</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/CSA_Suffix__c.field-meta.xml
<CustomField>
    <fullName>CSA_Suffix__c</fullName>
    <label>CSA Suffix</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation</label>
    <referenceTo>Implementation__c</referenceTo>
    <relationshipLabel>CSA&#39;s</relationshipLabel>
    <relationshipName>CSA_s</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CSA__c/fields/Medical_Drug_List__c.field-meta.xml
<CustomField>
    <fullName>Medical_Drug_List__c</fullName>
    <label>Medical Drug List</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRUDENTMED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Implementation__c/Implementation__c.object-meta.xml
<CustomObject>
    <label>Implementation</label>
    <nameField>
        <label>Implementation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Implementation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Implementations</relationshipLabel>
    <relationshipName>Implementations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Implementation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Implementations</relationshipLabel>
    <relationshipName>Implementations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Implementation__c/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <formula>Contract__r.Go_Live_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/CSAsSelector.cls
/**
 * @description       : CSA__c Selector Implementation
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             :
 * @last modified on  : 08-05-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log
 * Ver   Date         Author                           Modification
 * 1.0   08-05-2021   Ricardy Banks					   Initial Version
 *
 **/

public class CSAsSelector extends fflib_SObjectSelector
        implements ICSAsSelector
{

    public CSAsSelector() {
        super(false, true, true, false);
    }

    public static ICSAsSelector newInstance() {
        return (ICSAsSelector) PMd_Application.Selector.newInstance(CSA__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                CSA__c.Id,
                CSA__c.Name,
                CSA__c.Account__c,
                CSA__c.CSA_Account__c,
                CSA__c.CSA_Control__c,
                CSA__c.CreatedById,
                CSA__c.CSA_Number__c,
                CSA__c.Go_Live_Date__c,
                CSA__c.LastModifiedById,
                CSA__c.Medical_Drug_List__c,
                CSA__c.CSA_Suffix__c,
                CSA__c.LastModifiedById
        };
    }

    public Schema.SObjectType getSObjectType() {
        return CSA__c.SObjectType;
    }

    public List<CSA__c> selectById(Set<Id> idSet)
    {
        return (List<CSA__c>) selectSObjectsById(idSet);
    }

    public List<CSA__c> selectByCSANumber(Set<String> csaNumbers) {

        return (List<CSA__c>) Database.query(
                newQueryFactory().
                        selectField(CSA__c.Id).
                        selectField(CSA__c.Name).
                        selectField(CSA__c.Account__c).
                        selectField(CSA__c.CSA_Account__c).
                        selectField(CSA__c.CSA_Control__c).
                        selectField(CSA__c.CSA_Number__c).
                        selectField('Implementation__r.Contract__r.Go_Live_Date__c').
                        setCondition('CSA_Number__c IN :csaNumbers').
                        //setCondition('Patient_First_Name__c IN :firstName').
                        //setCondition('Patient_Last_Name__c IN :lastName').
                        toSOQL()
        );
    }

}