unpackaged/main/default/objects/Drug__c/Drug__c.object-meta.xml
<CustomObject>
    <description>The Main Drug Table</description>
    <label>Drug</label>
    <nameField>
        <label>Drug Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Drug__c/fields/Coding_Level__c.field-meta.xml
<CustomField>
    <fullName>Coding_Level__c</fullName>
    <label>Coding Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCPCS</fullName>
            </value>
            <value>
                <fullName>HCPCS + NDC</fullName>
            </value>
            <value>
                <fullName>HCPCS + DX</fullName>
            </value>
            <value>
                <fullName>ICD -10</fullName>
                <isActive>false</isActive>
                <label>ICD -10</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Drug__c/fields/J_Code__c.field-meta.xml
<CustomField>
    <fullName>J_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DrugsSelector.cls
/**
 * @description       : Drug__c Selector Implementation
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             :
 * @last modified on  : 08-05-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log
 * Ver   Date         Author                           Modification
 * 1.0   08-05-2021   Ricardy Banks					   Initial Version
 *
 **/
public class DrugsSelector extends fflib_SObjectSelector
        implements IDrugsSelector
{

    public DrugsSelector() {
        super(false, true, true, false);
    }

    public static DrugsSelector newInstance() {
        return (DrugsSelector) PMd_Application.Selector.newInstance(Drug__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Drug__c.Id,
                Drug__c.Name,
                Drug__c.J_Code__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Drug__c.SObjectType;
    }

    public List<Drug__c> selectById(Set<Id> idSet)
    {
        return (List<Drug__c>) selectSObjectsById(idSet);
    }

    public List<Drug__c> selectByHCPCSNumber(Set<String> hcpcsNumbers) {

        System.debug('hcpcsNumbers = ' + hcpcsNumbers);

        return (List<Drug__c>) Database.query(
                newQueryFactory().
                        selectField(Drug__c.Id).
                        selectField(Drug__c.Name).
                        selectField(Drug__c.J_Code__c).
                        selectField(Drug__c.Coding_Level__c).
                        setCondition('J_Code__c IN :hcpcsNumbers').
                        //setCondition('Patient_First_Name__c IN :firstName').
                        //setCondition('Patient_Last_Name__c IN :lastName').
                        toSOQL()
        );
    }
}