unpackaged/main/default/objects/Drug__c/Drug__c.object-meta.xml
<CustomObject>
    <description>The Main Drug Table</description>
    <label>Drug</label>
    <nameField>
        <label>Drug Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Drug__c/fields/Coding_Level__c.field-meta.xml
<CustomField>
    <fullName>Coding_Level__c</fullName>
    <label>Coding Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCPCS</fullName>
            </value>
            <value>
                <fullName>HCPCS + NDC</fullName>
            </value>
            <value>
                <fullName>HCPCS + DX</fullName>
            </value>
            <value>
                <fullName>ICD -10</fullName>
                <isActive>false</isActive>
                <label>ICD -10</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Drug__c/fields/J_Code__c.field-meta.xml
<CustomField>
    <fullName>J_Code__c</fullName>
    <label>HCPCS Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NDC__c/NDC__c.object-meta.xml
<CustomObject>
    <description>Drugs are identified and reported using a unique, three-segment number called the National Drug Code (NDC) which serves as the FDA’s identifier for drugs.</description>
    <label>NDC</label>
    <nameField>
        <label>NDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NDC__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>NDCs</relationshipLabel>
    <relationshipName>NDCs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/NDCsSelector.cls
/**
 * @description       : NDC__c Selector Implementation
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             :
 * @last modified on  : 05-24-2022
 * @last modified by  : Ricardy Banks
 * Modifications Log
 * Ver   Date         Author                           Modification
 * 1.0   05-24-2022   Ricardy Banks					   Initial Version: MBP-458 Business Logic: Update logic to match the correct Contact Drug based on inbound files
 *
 **/

public class NDCsSelector extends fflib_SObjectSelector
        implements INDCsSelector
{

    public NDCsSelector() {
        super(false, true, true, false);
    }

    public static NDCsSelector newInstance() {
        return (NDCsSelector) PMd_Application.Selector.newInstance(NDC__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                NDC__c.Id,
                NDC__c.Name,
                NDC__c.Drug__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return NDC__c.SObjectType;
    }

    public List<NDC__c> selectById(Set<Id> idSet)
    {
        return (List<NDC__c>) selectSObjectsById(idSet);
    }

    public List<NDC__c> selectByDrugId(Set<Id> drugIds) {

        System.debug('drugIds = ' + drugIds);

        return (List<NDC__c>) Database.query(
                newQueryFactory().
                        selectField(NDC__c.Id).
                        selectField(NDC__c.Name).
                        selectField('Drug__r.J_Code__c').
                        selectField('Drug__r.Coding_Level__c').
                        setCondition('Drug__c IN :drugIds').
                        toSOQL()
        );
    }
}