unpackaged/main/default/objects/Daily_Claim__c/Daily_Claim__c.object-meta.xml
<CustomObject>
    <label>Daily Claim</label>
    <nameField>
        <displayFormat>DC-{0000000}</displayFormat>
        <label>Daily Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Daily_Claim__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <description>If HCPCS does not exist on Drug object, then don’t process record and set:
     - Status [NEW FIELD] to “Error”
     - Error Log [NEW FIELD] to “HCPCS Mismatch.” Dependent and connected to the Status field.</description>
    <label>Error Log</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>HCPCS Mismatch</fullName>
            </value>
            <value>
                <fullName>CSA Mismatch</fullName>
            </value>
            <value>
                <fullName>Previous segment not found</fullName>
            </value>
            <value>
                <fullName>Unable to create record due to duplicate.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Error_Log__c/fields/API_Request__c.field-meta.xml
<CustomField>
    <fullName>API_Request__c</fullName>
    <label>API Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/API_Response__c.field-meta.xml
<CustomField>
    <fullName>API_Response__c</fullName>
    <label>API Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Daily_Claim__c.field-meta.xml
<CustomField>
    <fullName>Daily_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Claim</label>
    <referenceTo>Daily_Claim__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Historical_Claim__c.field-meta.xml
<CustomField>
    <fullName>Historical_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Historical Claim record.</description>
    <label>Historical Claim</label>
    <referenceTo>Historical_Claim__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Historical_Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Historical_Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Historical Prior Auth record.</description>
    <label>Historical Prior Auth</label>
    <referenceTo>Historical_Prior_Auth__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Prior_Auth__c.field-meta.xml
<CustomField>
    <fullName>Prior_Auth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Prior Auth record.</description>
    <label>Prior Auth</label>
    <referenceTo>Prior_Auth__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historical_Claim__c/Historical_Claim__c.object-meta.xml
<CustomObject>
    <label>Historical Claim</label>
    <nameField>
        <displayFormat>HC-{0000000}</displayFormat>
        <label>Historical Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historical_Prior_Auth__c/Historical_Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Historical Prior Auth</label>
    <nameField>
        <displayFormat>HPA-{0000000}</displayFormat>
        <label>Historical Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prior_Auth__c/Prior_Auth__c.object-meta.xml
<CustomObject>
    <label>Prior Auth</label>
    <nameField>
        <displayFormat>DPA-{0000000}</displayFormat>
        <label>Prior Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prior Auth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prior_Auth__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCPCS Mismatch</fullName>
            </value>
            <value>
                <fullName>CSA Mismatch</fullName>
            </value>
            <value>
                <fullName>Unable to create record due to duplicate.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ErrorLog.cls
public class ErrorLog {
    public static List<Error_Log__c> logList = new List<Error_Log__c>();

    public static void log(String method, String endpoint, String requestBody, String responseBody, String errorCode, String errorMessage,
    Id dailyClaimRecordId) {
        ErrorLog.log(method, endpoint, requestBody, responseBody, errorCode, errorMessage, dailyClaimRecordId,null, null, null);
    }
    
    public static void log(String method, String endpoint, String requestBody, String responseBody, String errorCode, String errorMessage,
                            Id dailyClaimRecordId, Id historicalClaimId, Id priorAuthId, Id historicalPriorAuthId){

        Error_Log__c integrationLog = new Error_Log__c();
        if(dailyClaimRecordId != null){
            integrationLog.Daily_Claim__c = dailyClaimRecordId;
        }
        if(historicalClaimId != null){
            integrationLog.Historical_Claim__c = historicalClaimId;
        }
        if(priorAuthId != null){
            integrationLog.Prior_Auth__c = priorAuthId;
        }
        if(historicalPriorAuthId != null){
            integrationLog.Historical_Prior_Auth__c = historicalPriorAuthId;
        }

        integrationLog.Method__c = method;
        integrationLog.Endpoint__c = endpoint;
        if(String.isEmpty(requestBody) != true){
            integrationLog.API_Request__c = requestBody;
        }
        
        if(String.isEmpty(responseBody) != true){
            integrationLog.API_Response__c = responseBody;
        }
        
        integrationLog.Error_Code__c = errorCode;
        integrationLog.Error_Message__c = errorMessage;
        logList.add(integrationLog);

        String emailBody = method + '<p>' + errorMessage;
        ErrorLog.sendErrorLogEmail('Error processing ' + method, emailBody);
    }
    
    public static void commitLogs(){
        if(logList.size() > 0){
            upsert logList;
        }
    }

    // Simple notification of any errors received via email
    public static void sendErrorLogEmail(String emailSubject, String emailBody) {

            // Email address from user
            Map<Id, String> usersEmail =
                    new UsersSelector().getUsersEmail(
                            new Set<Id> { UserInfo.getUserId() });

            // Send email
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new String[] { 'salesforce_development_team@prudentrx.com' });
            mail.setReplyTo('salesforce_development_team@prudentrx.com');
            mail.setSenderDisplayName('salesforce_development_team');
            mail.setSubject(emailSubject);
            mail.setHtmlBody(emailBody);
            //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

    }
}