unpackaged/main/default/objects/Daily_Claim__c/Daily_Claim__c.object-meta.xml
<CustomObject>
    <label>Daily Claim</label>
    <nameField>
        <displayFormat>DC-{0000000}</displayFormat>
        <label>Daily Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Daily_Claim__c/fields/Billing_Provider_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_First_Name__c</fullName>
    <label>Billing Provider First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Daily Claims</relationshipLabel>
    <relationshipName>Daily_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Claim_Code__c.field-meta.xml
<CustomField>
    <fullName>Claim_Code__c</fullName>
    <label>Claim Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Claim_Line__c.field-meta.xml
<CustomField>
    <fullName>Claim_Line__c</fullName>
    <label>Claim Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Claim_Segment__c.field-meta.xml
<CustomField>
    <fullName>Claim_Segment__c</fullName>
    <label>Claim Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/CSA_Account__c.field-meta.xml
<CustomField>
    <fullName>CSA_Account__c</fullName>
    <label>CSA Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Previous_Segment__c.field-meta.xml
<CustomField>
    <fullName>Previous_Segment__c</fullName>
    <label>Previous Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Primary_Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Claim_Number__c</fullName>
    <label>Primary Claim Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Go-live Date Null</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Daily_ClaimsSelector.cls
/**
 * @description       : This is a basic selector for Daily_Claim__c for this app.
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             : 
 * @last modified on  : 08-08-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log 
 * Ver   Date         Author                           Modification
 * 1.0   08-06-2021   Ricardy Banks					   Initial Version
 * 
 **/

public class Daily_ClaimsSelector extends fflib_SObjectSelector 
    implements IDaily_ClaimsSelector 
{

    public Daily_ClaimsSelector() {
        super(false, true, true, false);
    }

    public static IDaily_ClaimsSelector newInstance() {
        return (IDaily_ClaimsSelector) PMd_Application.Selector.newInstance(Daily_Claim__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Daily_Claim__c.Id,
            Daily_Claim__c.Name,
            Daily_Claim__c.CSA_Account__c,
            Daily_Claim__c.Primary_Claim_Number__c,
            Daily_Claim__c.Claim_Code__c,
            Daily_Claim__c.Billing_Provider_First_Name__c,
            Daily_Claim__c.COB_Code__c,
            Daily_Claim__c.Case__c,
            Daily_Claim__c.Status__c
        };
    }

    public Schema.SObjectType getSObjectType()
    {
        return Daily_Claim__c.SObjectType;
    }

    public List<Daily_Claim__c> selectById(Set<Id> idSet)
    {
        return (List<Daily_Claim__c>) selectSObjectsById(idSet);
    }

    public List<Daily_Claim__c> selectByClaim_Number(Set<String> claim_NumberSet) {

        return (List<Daily_Claim__c>) Database.query(
                newQueryFactory().
                        selectField(Daily_Claim__c.Id).
                        selectField(Daily_Claim__c.OwnerId).
                        selectField(Daily_Claim__c.Name).
                        selectField(Daily_Claim__c.Primary_Claim_Number__c).
                        selectField(Daily_Claim__c.Claim_Segment__c).
                        selectField(Daily_Claim__c.Claim_Line__c).
                        selectField(Daily_Claim__c.Previous_Segment__c).
                        selectField(Daily_Claim__c.Claim_Number__c).
                        setCondition('Claim_Number__c IN :claim_NumberSet').
                        toSOQL()
        );
    }

}