unpackaged/main/default/objects/Daily_Claim__c/Daily_Claim__c.object-meta.xml
<CustomObject>
    <label>Daily Claim</label>
    <nameField>
        <displayFormat>DC-{0000000}</displayFormat>
        <label>Daily Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Daily_Claim__c/fields/Amount_Paid_By_Primary__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid_By_Primary__c</fullName>
    <label>Amount Paid By Primary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Authorized_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Relationship__c</fullName>
    <label>Authorized Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Authorized_Representative__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Representative__c</fullName>
    <label>Authorized Representative</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Billing_Provider_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_Address_Line_1__c</fullName>
    <label>Billing Provider Address Line 1</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Billing_Provider_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_First_Name__c</fullName>
    <label>Billing Provider First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Billing_Provider_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_Last_Name__c</fullName>
    <label>Billing Provider Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Billing_Provider_Specialty__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_Specialty__c</fullName>
    <label>Billing Provider Specialty</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Billing_Provider_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_State__c</fullName>
    <label>Billing Provider State</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Billing_Provider_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_Zip_Code__c</fullName>
    <label>Billing Provider Zip Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Claim_Code__c.field-meta.xml
<CustomField>
    <fullName>Claim_Code__c</fullName>
    <label>Claim Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Claim_Line__c.field-meta.xml
<CustomField>
    <fullName>Claim_Line__c</fullName>
    <label>Claim Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Claim_Segment__c.field-meta.xml
<CustomField>
    <fullName>Claim_Segment__c</fullName>
    <label>Claim Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/CSA_Account__c.field-meta.xml
<CustomField>
    <fullName>CSA_Account__c</fullName>
    <label>CSA Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/CSA_Control__c.field-meta.xml
<CustomField>
    <fullName>CSA_Control__c</fullName>
    <description>A subdivision of a purchaser.  These subdivisions are designated by the purchaser and Aetna for reporting, administrative, and accounting needs
(specifically to summarize/combine suffixes).  A CONTROL will always be associated with at least one SUFFIX.  A CONTROL will always be associated with one and only one purchaser.</description>
    <label>CSA Control</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/CSA_Number__c.field-meta.xml
<CustomField>
    <fullName>CSA_Number__c</fullName>
    <description>SHA1 has number created from Control+Suffix+Account</description>
    <label>CSA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/CSA_Suffix__c.field-meta.xml
<CustomField>
    <fullName>CSA_Suffix__c</fullName>
    <description>This is a subdivision of a control.  These subdivisions are designated  by the purchaser and Aetna for reporting administrative and accounting needs (specifically to summarize/combine accounts).  A SUFFIX will always be associated to one and only one
CONTROL.  A SUFFIX will always be associated with at least one ACCOUNT.</description>
    <label>CSA Suffix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Date_Of_Service_From__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Service_From__c</fullName>
    <label>Date of Service From</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Days_Supply__c.field-meta.xml
<CustomField>
    <fullName>Days_Supply__c</fullName>
    <label>Days Supply</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Diagnosis_Code__c.field-meta.xml
<CustomField>
    <fullName>Diagnosis_Code__c</fullName>
    <label>Diagnosis Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/NDC__c.field-meta.xml
<CustomField>
    <fullName>NDC__c</fullName>
    <label>NDC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Patient_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Patient_Address_Line_1__c</fullName>
    <label>Patient Address Line 1</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Patient_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Patient_Address_Line_2__c</fullName>
    <label>Patient Address Line 2</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Patient_City__c.field-meta.xml
<CustomField>
    <fullName>Patient_City__c</fullName>
    <label>Patient City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Patient_CUMB_ID__c.field-meta.xml
<CustomField>
    <fullName>Patient_CUMB_ID__c</fullName>
    <description>The customer member number assigned to the subscriber</description>
    <label>Patient CUMB ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Patient_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_First_Name__c</fullName>
    <label>Patient First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Patient_Gender__c.field-meta.xml
<CustomField>
    <fullName>Patient_Gender__c</fullName>
    <label>Patient Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
                <isActive>false</isActive>
                <label>Female</label>
            </value>
            <value>
                <fullName>Male</fullName>
                <isActive>false</isActive>
                <label>Male</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Patient_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Last_Name__c</fullName>
    <label>Patient Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Plan_Sponsor_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Sponsor_Name__c</fullName>
    <description>&quot;The name of the policy holder
CMT:  Also known as Customer, Plan Sponsor&quot;</description>
    <label>Plan Sponsor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Preferred_Provider__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Provider__c</fullName>
    <label>Preferred Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Previous_Claim__c.field-meta.xml
<CustomField>
    <fullName>Previous_Claim__c</fullName>
    <label>Previous Claim</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Primary_Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Claim_Number__c</fullName>
    <label>Primary Claim Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Relationship_Code__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Code__c</fullName>
    <description>A code which identifies the patient&#39;s relationship to the member</description>
    <label>Relationship Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Service_Provider_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Address_Line_1__c</fullName>
    <label>Service Provider Address Line 1</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Service_Provider_City__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_City__c</fullName>
    <label>Service Provider City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Service_Provider_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_First_Name__c</fullName>
    <label>Service Provider First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Service_Provider_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Last_Name__c</fullName>
    <label>Service Provider Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Service_Provider_State__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_State__c</fullName>
    <label>Service Provider State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Service_Provider_Zip__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Zip__c</fullName>
    <label>Service Provider Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Total_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>Total_Coinsurance__c</fullName>
    <label>Total Coinsurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Daily_Claim__c/fields/Units_Billed__c.field-meta.xml
<CustomField>
    <fullName>Units_Billed__c</fullName>
    <label>Units Billed</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/NDC__c/NDC__c.object-meta.xml
<CustomObject>
    <description>Drugs are identified and reported using a unique, three-segment number called the National Drug Code (NDC) which serves as the FDA’s identifier for drugs.</description>
    <label>NDC</label>
    <nameField>
        <label>NDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NDCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/Daily_ClaimsSelectorTest.cls
/**
 * @description       :
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             :
 * @last modified on  : 08-06-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log
 * Ver   Date         Author                           Modification
 * 1.0   08-06-2021   Ricardy Banks             Initial Version
 *
 **/
@IsTest
private class Daily_ClaimsSelectorTest {

    @IsTest
    private static void testSelectById()
    {
        // Test data
        Daily_Claim__c dailyClaims = new Daily_Claim__c();
        dailyClaims.CSA_Account__c = 'AN0005';
        dailyClaims.Units_Billed__c = 2;
        dailyClaims.Amount_Paid_By_Primary__c = 100;
        dailyClaims.Prior_Authorization__c = 'A123';
        dailyClaims.Authorized_Representative__c = 'Jane Smith';
        dailyClaims.Authorized_Relationship__c = '1';
        dailyClaims.Billing_Provider_City__c = 'New York City';
        dailyClaims.Billing_Provider_First_Name__c = 'Test';
        dailyClaims.Billing_Provider_Last_Name__c = 'one';
        dailyClaims.Billing_Provider_Specialty__c = 'Specialty 1';
        dailyClaims.Billing_Provider_PIN__c = '1234567';
        dailyClaims.Billing_Provider_State__c = 'NY';
        dailyClaims.Billing_Provider_Address_Line_1__c = '456 Test Lane';
        dailyClaims.Billing_Provider_Zip_Code__c = '10123';
        dailyClaims.Billing_Provider_Phone__c = '5555555555';
        dailyClaims.Billing_Provider_Fax__c = '9999999999';
        dailyClaims.Primary_Claim_Number__c = 'E11111111111111';
        dailyClaims.Claim_Code__c = 'Initial Claim';
        dailyClaims.Claim_Line__c = '1';
        dailyClaims.Claim_Segment__c = '01';
        dailyClaims.COB_Code__c = 'Secondary';
        dailyClaims.CSA_Control__c = 'CN0005';
        dailyClaims.Days_Supply__c = 30;
        dailyClaims.Diagnosis_Code__c = '12345678987';
        dailyClaims.Drug_Label_Name__c = 'Drug One';
        dailyClaims.HCPCS_Code__c = 'J5678';
        dailyClaims.NDC__c = '123456789';
        dailyClaims.PA_Approval_Dates__c = date.valueOf('2021-07-01');
        //dailyClaims.Patient_Birth_Date__c = date.valueOf('1990-01-01');
        //dailyClaims.Patient_Email_Address__c = 'jsmith@test.com';
        dailyClaims.Patient_First_Name__c = 'Joe';
        dailyClaims.Patient_Last_Name__c = 'Smith';
        dailyClaims.Patient_Middle_Initial__c = 'H';
        dailyClaims.Patient_Phone_Number__c = '8888888888';
        dailyClaims.Patient_Gender__c = 'M';
        dailyClaims.Plan_Sponsor_Name__c = 'Sample Company';
        dailyClaims.Preferred_Provider__c = 'Preferred';
        dailyClaims.Date_Of_Service_From__c = date.valueOf('2021-07-01');
        dailyClaims.Service_Provider_Fax__c = '5555555555';
        dailyClaims.Service_Provider_Phone__c = '7777777777';
        dailyClaims.Date_Of_Service_To__c = date.valueOf('2021-07-02');
        dailyClaims.Service_Provider_Address_Line_1__c = '456 plane Lane';
        dailyClaims.Service_Provider_City__c = 'Chicago';
        dailyClaims.Service_Provider_First_Name__c = 'Jane';
        dailyClaims.Service_Provider_Last_Name__c = 'Doe';
        dailyClaims.Service_Provider_NPI__c = '9998887776';
        //dailyClaims.Service_Provider_Practice__c = 'NONE';
        dailyClaims.Service_Provider_Zip__c = '10123';
        dailyClaims.Service_Provider_State__c = 'NY';
        dailyClaims.Patient_Address_Line_1__c = '123 Sesame Street';
        dailyClaims.Patient_Address_Line_2__c = '0';
        dailyClaims.Patient_City__c = 'Los Angeles';
        dailyClaims.Patient_CUMB_ID__c = 'W12345678';
        dailyClaims.Patient_State__c = 'NY';
        dailyClaims.Patient_Zip_Code__c = '10151';
        dailyClaims.CSA_Suffix__c = 'SN0005';
        dailyClaims.Total_Coinsurance__c = 30;
        dailyClaims.Total_Copay__c = 30;
        dailyClaims.Total_Deductible__c = 500;
        dailyClaims.Previous_Claim__c = '';
        dailyClaims.Relationship_Code__c = '01';
        //dailyClaims.CSA_Number__c = SHA1UtilService.getBase64SHA1Hash('CN0003' + 'SN0003' +'AN0003');
        //
        insert dailyClaims;

        // Query
        List<Daily_Claim__c> dailyClaimsList =
                new Daily_ClaimsSelector().selectById(new Set<Id> { dailyClaims.Id });

        // Assert
        //System.assertEquals('Something cool', dailyClaims[0].Billing_Provider_First_Name__c);
        //System.assertEquals('CoolName', dailyClaims[0].Name);
    }
}