unpackaged/main/default/objects/Daily_Claim__c/Daily_Claim__c.object-meta.xml
<CustomObject>
    <label>Daily Claim</label>
    <nameField>
        <displayFormat>DC-{0000000}</displayFormat>
        <label>Daily Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Daily_Claim__c/fields/Billing_Provider_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Provider_First_Name__c</fullName>
    <label>Billing Provider First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TestDaily_ClaimsSelector.cls
/**
 * @description       : 
 * @author            : Ricardy.Banks@PrudentRx.com
 * @group             : 
 * @last modified on  : 08-06-2021
 * @last modified by  : Ricardy Banks
 * Modifications Log 
 * Ver   Date         Author                           Modification
 * 1.0   08-06-2021   Ricardy Banks					   Initial Version
 * 
 **/
@IsTest
private class TestDaily_ClaimsSelector {

	@IsTest
	private static void testSelectById()
	{
		/*
		// Test data
		Daily_Claim__c dailyClaim = new Daily_Claim__c();
		//dailyClaim.Billing_Provider_First_Name__c = 'Something cool';
		//dailyClaim.Name = 'CoolName';
		insert dailyClaim;
				
		// Query
		List<Daily_Claim__c> dailyClaims = 
			new Daily_ClaimsSelector().selectById(new Set<Id> { dailyClaim.Id });
			
		// Assert
		//System.assertEquals('Something cool', dailyClaims[0].Billing_Provider_First_Name__c);
		System.assertEquals('CoolName', dailyClaims[0].Name);
		*/
	}
}